### ISSUE TITLE
cronet 随机回退到 TCP 连接导致被重置

### ISSUE THREAD

**Issue by iiikunn** [UjuiUjuMandan/EhViewer#1]
### 复现步骤 / Step to reproduce

如上

### 预期行为 / Expected behaviour

直连ex

### 实际行为 / Actual Behaviour

出现“奇怪的错误”提示

### EhViewer 版本号 / EhViewer version code

1.8.9.7

### EhViewer CI 版本 / EhViewer CI Version

8e8706b

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

红米12turbo

### SoC 型号 / Soc model

7gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
我想要帮忙，但是你提供的信息有点少。

1. 画廊站点切到 e-hentai 能访问吗？
2. 浏览器能否访问 https://skk.moe ？
3. 什么运营商？

**Comment by UjuiUjuMandan** [comment]
我刚才使用了一个没有 exhentai 权限的帐号来测试：画廊站点为 exhentai 时，访问收藏会显示“奇怪的错误”、其他页面会显示“空页面”。

错误在于，此处应该显示“Sad Panda”来提示用户其没有权限，而不是显示如上所述的内容。

我觉得你的帐号是否只是简单地没有 exhentai 权限呢？你在浏览器登陆后能够访问 exhentai 呢？

**Comment by iiikunn** [comment]
感谢。
1、可以
2、可以
3、联通
4、安卓13
刚刚尝试了一下，使用联通的流量进入成功，但是更换网络后就无法访问了（比如在不关闭流量的情况下连接WIFI，并且刷新页面，就会在短暂转圈后提示奇怪的错误。此时，关闭WIFI，切换回流量也无法访问，重启软件也是。但是随意挂一个区域的梯子，哪怕是香港，可以访问）。
具体触发条件似乎是 进入EHviewer→更换网络→刷新页面，之后就会转圈然后提示奇怪的错误。但是似乎过一段时间就会恢复？如果需要log文件我可以提供。

**Comment by iiikunn** [comment]
比较奇怪的是，刚刚在反馈过程中，我再次尝试进入里站，成功了。十分钟前我刚刚尝试更换网络操作并出现奇怪的错误，现在却又可以借助流量访问了。中途没有再切换网络。

**Comment by iiikunn** [comment]
呃，刚刚打字过程中再切回去，又变成了奇怪的错误🧐

**Comment by UjuiUjuMandan** [comment]
@iiikunn 麻烦提供日志，复现一次“奇怪的错误”之后使用 设置-高级-导出日志 。
另外请试试这个版本看报错为何: https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6464693427 。

**Comment by iiikunn** [comment]
感谢。
不管是更新前还是更新后，都是根本进不去
然后提示奇怪的错误。
联通直连。
1log是更新前的log
2log是更新后的log

通过百度网盘分享的文件：log
链接:https://pan.baidu.com/s/10HoImARY1xr_B1jpUyfNFQ?pwd=119f 
提取码:119f
复制这段内容打开「百度网盘APP 即可获取」

**Comment by UjuiUjuMandan** [comment]
```
10-10 12:43:58.694 18693 29603 D EhEngine: https://exhentai.org/
10-10 12:43:59.127 18693 18693 W System.err: java.io.IOException: java.util.concurrent.ExecutionException: zj0: Exception in CronetUrlRequest: net::ERR_CONNECTION_RESET, ErrorCode=8, InternalErrorCode=-101, Retryable=true
```

@FooIBar 来看看为啥会这样呢？addQuicHint 里有 exhentai.org ，用了 QUIC 还能被 RESET ？

**Comment by UjuiUjuMandan** [comment]
@iiikunn 你有电脑吗？用 Chromium 内核的浏览器，在其快捷方式的“目标” 后加入

```
  --enable-quic --origin-to-force-quic-on="exhentai.org:443, forums.e-hentai.org:443" --host-resolver-rules="MAP forums.e-hentai.org skk.moe, MAP exhentai.org skk.moe" 
```

然后打开它，访问 https://exhentai.org 。看看能正常看到白屏还是有别的错误。

**Comment by lukemin** [comment]
[logcat-2023-10-10-13-33-15-877.txt](https://github.com/UjuiUjuMandan/EhViewer/files/12853221/logcat-2023-10-10-13-33-15-877.txt)
我的也是显示奇怪的错误。用的最新版的ci版本

**Comment by lukemin** [comment]
> @iiikunn 你有电脑吗？对 Chromium 内核的浏览器，在其快捷方式的“目标” 后加入
> 
> ```
>  --enable-quic --origin-to-force-quic-on="exhentai.org:443, forums.e-hentai.org:443" --host-resolver-rules="MAP forums.e-hentai.org skk.moe, MAP exhentai.org skk.moe" 
> ```
> 
> 然后打开它，访问 https://exhentai.org 。看看能正常看到白屏还是有别的错误。

结果是 ERR_CONNECTION_TIMED_OUT

**Comment by UjuiUjuMandan** [comment]
> 结果是 ERR_CONNECTION_TIMED_OUT

那应该是访问 `skk.moe` 的 IP 时超时罢，把 2 个 `skk.moe` 更换为比如 `dash.cloudflare.com` 或者 `cdn.sstatic.net` 呢？

**Comment by lukemin** [comment]
> cdn.sstatic.net

"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --enable-quic --origin-to-force-quic-on="exhentai.org:443, forums.e-hentai.org:443" --host-resolver-rules="MAP forums.e-hentai.org cdn.sstatic.net, MAP exhentai.org cdn.sstatic.net"

"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --enable-quic --origin-to-force-quic-on="exhentai.org:443, forums.e-hentai.org:443" --host-resolver-rules="MAP forums.e-hentai.org dash.cloudflare.com, MAP exhentai.org dash.cloudflare.com"

都试了，一样的结果

**Comment by UjuiUjuMandan** [comment]
> 都试了，一样的结果

绷...难不成所有 Cloudflare 的 IP 在你地区都被封锁了...还是因为对 Edge 所以这些参数不生效...

**Comment by lukemin** [comment]
没有，我可以直连 Cloudflare.com

**Comment by iiikunn** [comment]
> @iiikunn 你有电脑吗？对 Chromium 内核的浏览器，在其快捷方式的“目标” 后加入
> 
> ```
>  --enable-quic --origin-to-force-quic-on="exhentai.org:443, forums.e-hentai.org:443" --host-resolver-rules="MAP forums.e-hentai.org skk.moe, MAP exhentai.org skk.moe" 
> ```
> 
> 然后打开它，访问 https://exhentai.org 。看看能正常看到白屏还是有别的错误。

我在上课，稍等，谷歌浏览器可以吗

**Comment by iiikunn** [comment]
> @iiikunn 你有电脑吗？对 Chromium 内核的浏览器，在其快捷方式的“目标” 后加入
> 
> ```
>  --enable-quic --origin-to-force-quic-on="exhentai.org:443, forums.e-hentai.org:443" --host-resolver-rules="MAP forums.e-hentai.org skk.moe, MAP exhentai.org skk.moe" 
> ```
> 
> 然后打开它，访问 https://exhentai.org 。看看能正常看到白屏还是有别的错误。

尝试过了，如果关闭VPN，可以加载出白屏。开VPN还没试过

**Comment by iiikunn** [comment]
请问还需要别的支持吗？

**Comment by iiikunn** [comment]
> > 请问还需要别的支持吗？
> 
> 我复现不了，所以修不了。

感谢。就这样吧。
另外，或许作者您可以通过上一位维护者寻求支持。听说他的版本依旧可用。

**Comment by UjuiUjuMandan** [comment]
QUIC 只在第一次连接时被使用，失败就会回退 TCP ，被重置。查了没有禁用回退的方法。

**Comment by UjuiUjuMandan** [comment]
那么为什么会失败呢？肯定是指定的 Cloudflare IP 连通性不够好。目前是硬编码了 skk.moe ，未来可能会让使用者自定要 MAP 到什么 域名/IP 。

**Comment by Pantyhose-X** [comment]
> 感谢。 1、可以 2、可以 3、联通 4、安卓13 刚刚尝试了一下，使用联通的流量进入成功，但是更换网络后就无法访问了（比如在不关闭流量的情况下连接WIFI，并且刷新页面，就会在短暂转圈后提示奇怪的错误。此时，关闭WIFI，切换回流量也无法访问，重启软件也是。但是随意挂一个区域的梯子，哪怕是香港，可以访问）。 具体触发条件似乎是 进入EHviewer→更换网络→刷新页面，之后就会转圈然后提示奇怪的错误。但是似乎过一段时间就会恢复？如果需要log文件我可以提供。

WiFi更改DNS
SIM卡修改APN設置

**Comment by UjuiUjuMandan** [comment]
> 那么为什么会失败呢？肯定是指定的 Cloudflare IP 连通性不够好。目前是硬编码了 [skk.moe](https://skk.moe) ，未来可能会让使用者自定要 MAP 到什么 域名/IP 。

除了在 Cloudflare IP Override 中自选 IP 之外，也可以直接不用 Cronet ，选择 OkHttp ，这会让他回到域前置。
