### ISSUE TITLE
直连失败，刷新一直出现网络错误

### ISSUE THREAD

**Issue by ndnxnxnx** [UjuiUjuMandan/EhViewer#11]
### 复现步骤 / Step to reproduce

打开app出现主页

### 预期行为 / Expected behaviour

打开app出现主页

### 实际行为 / Actual Behaviour

![Screenshot_2023-10-28-20-38-41-420_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/117420395/db089963-2e04-4d92-b096-27b2eb96b6d7)

### 应用日志 / App logs

[log-2023-10-28-20-39-08-246.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13195791/log-2023-10-28-20-39-08-246.zip)

### 备注 / Addition details

无

### EhViewer 版本号 / EhViewer version code

1.8.10.2

### EhViewer CI 版本 / EhViewer CI Version

03f3b9c

### Android 系统版本 / Android version

miui 13.0.7 p

### 设备型号 / Device model

红米k50u

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
你没开 cronet 吧，开了不会是 `java.net...` 这种错误。

**Comment by ndnxnxnx** [comment]
> 你没开 cronet 吧，开了不会是 `java.net...` 这种错误。

打开了也不行

**Comment by ndnxnxnx** [comment]
> > 你没开 cronet 吧，开了不会是 `java.net...` 这种错误。
> 
> 打开了也不行



> 你没开 cronet 吧，开了不会是 `java.net...` 这种错误。

确实
