### ISSUE TITLE
里站显示 host unreachable

### ISSUE THREAD

**Issue by jeff20000112** [UjuiUjuMandan/EhViewer#112]
### 复现步骤 / Step to reproduce

打开vpn美国节点 打开彩e app，选择cookie登录，填写ipb_member_id和ipb_pass_hash，igneous空着，登录。切换到exhentai。

### 预期行为 / Expected behaviour

他应该可以正常显示

### 实际行为 / Actual Behaviour

![Screenshot_2024-12-09-05-54-03-64_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/889c8c34-3971-438e-b50a-60aefaefa8dc)

### 应用日志 / App logs

[log-2024-12-09-06-06-03-396.zip](https://github.com/user-attachments/files/18054166/log-2024-12-09-06-06-03-396.zip)

### 备注 / Addition details

打开vpn美国节点 打开彩e app，选择cookie登录，填写ipb_member_id和ipb_pass_hash，igneous空着，登录。切换到exhentai。
也尝试过使用美国节点网页登录，同样无法打开exhentai。绿e倒是可以正常使用里站。账号無问题，老账号了一直都是正常使用

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13.1-cc

### EhViewer CI 版本 / EhViewer CI Version

1.13.1-cc 7c1a3ab

### Android 系统版本 / Android version

coloros v12.1

### 设备型号 / Device model

OPPO Reno3

### SoC 型号 / Soc model

disenmsity 1000L

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by jeff20000112** [comment]
![Screenshot_2024-12-10-09-40-09-33_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/bb2aa2aa-79a9-4ddb-b895-b464b5278a39)

之前一直没问题的，就是这两个版本才出现的问题，上一个版本的app通过美国节点vpn网页登录可以打开里站，但是这个版本似乎这个方法也没有用了

**Comment by jeff20000112** [comment]
![Screenshot_2024-12-10-09-48-30-82_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/ff055839-9b96-4b36-888f-bac728d98938)

尝试将引擎更改为cronet解决了问题，现在可以正常进入里站

**Comment by jeff20000112** [comment]
> e-hentai 没问题只有 exhentai 会这么出错吗？那我怀疑这是因为你的网络本身有 IPv6 出口但是你的代理没有。

![Screenshot_2024-12-10-22-59-32-91_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/bb37f104-dc9d-407a-9b8e-ab56af144008)
![Screenshot_2024-12-10-22-59-22-23_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/9c44a8d8-7b51-4415-8120-5d4fa91487eb)
版本应该没有问题吧？检查更新也显示是最新版本。我是第一次提交问题，有很多弄得不对的地方请见谅。在http引擎为okhttp的时候，会显示host unreachable。

**Comment by midknightblu1** [comment]
![Screenshot_2024-12-10-22-15-34-37_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/0d09f63b-69af-4299-892e-e5c34f973788)
I cannot reach the host either. sadly dont understand whats going on in the thread above to know what measures to take (if any) kr what questions to answer.

All I can say is it's been this way since the latest update was pushed out.

**Comment by jeff20000112** [comment]
> 控制 Http 引擎不变。
> 
> 画廊站点	Encrypted Client Hello	出现 host unreachable
> e-hentai	开启	A
> e-hentai	关闭	B
> exhentai	开启	C
> exhentai	关闭	D
> 开启或关闭后需要重启应用。
> 
> 请告诉我 A、B、C、D 是或者否？
> 
> 将你的 VPN 设置为全局模式访问 https://ipleak.net 显示为何？只有 IPv4、只有 IPv6 或者两者都有？

vpn访问上面的网站只显示ipv4。ABCD四种情况全部不会显示host unreachable。版本检查显示已经是最新版本了。甚至将http引擎切换为okhttp也不会再显示host reachable了。很奇怪😓
