### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by ndnxnxnx** [UjuiUjuMandan/EhViewer#12]
### 复现步骤 / Step to reproduce

翻漫画时闪退

### 预期行为 / Expected behaviour

不会闪退

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[log-2023-10-29-00-25-01-712.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13196289/log-2023-10-29-00-25-01-712.zip)

### EhViewer 版本号 / EhViewer version code

1.8.10.2

### EhViewer CI 版本 / EhViewer CI Version

03f3b9c

### Android 系统版本 / Android version

miui13.0.7

### 设备型号 / Device model

红米k50u

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
建议搞清楚如何复现然后找 [FooIbar](https://github.com/FooIbar/EhViewer)提。
