### ISSUE TITLE
在Ehviewer的“关于”里添加作者的名字

### ISSUE THREAD

**Issue by RxinnotRstar** [UjuiUjuMandan/EhViewer#14]
### 复现步骤 / Step to reproduce

打开应用
↓
设置
↓
关于
↓
阅读“作者”区域

### 预期行为 / Expected behaviour

` Foolbar & UjuiUjuMandan(patch) `

### 实际行为 / Actual Behaviour

`Foolbar`
![IMG_20231031_144925](https://github.com/UjuiUjuMandan/EhViewer/assets/56676566/e140096d-436f-495d-bcff-5c4a9863bfff)

### 应用日志 / App logs

-

### 备注 / Addition details

毕竟您也是该项目的参与者，您应该在上面留名。

### 浏览站点 / Browsing site

-

### EhViewer 版本号 / EhViewer version code

1.8.11.0

### EhViewer CI 版本 / EhViewer CI Version

-

### Android 系统版本 / Android version

-

### 设备型号 / Device model

-

### SoC 型号 / Soc model

-

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
UUM 这个名字是仿冒某维基人的，我并不想透露或留下我的任何名字。
