### ISSUE TITLE
是否能够优化滑动感

### ISSUE THREAD

**Issue by emmpp** [UjuiUjuMandan/EhViewer#15]
### 复现步骤 / Step to reproduce

上下滑动出现卡顿甚至划不动或者莫名变成左右滑动
![Screenshot_20231031_192949](https://github.com/UjuiUjuMandan/EhViewer/assets/149444278/948695d5-63cc-4699-864d-7532776c25ea)

### 预期行为 / Expected behaviour

希望可以优化一下，提高流畅不在上下卡顿和莫名的左右判定

### 实际行为 / Actual Behaviour

![Screenshot_20231031_192949](https://github.com/UjuiUjuMandan/EhViewer/assets/149444278/6424d562-0743-42f4-abf8-382b3f9e4e54)

### 应用日志 / App logs

有些时候会莫名划不动一直卡着

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.8.11.0

### EhViewer CI 版本 / EhViewer CI Version

3d5c3a6

### Android 系统版本 / Android version

13

### 设备型号 / Device model

xiaomi12utra

### SoC 型号 / Soc model

骁龙8

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
本分支不处理这些问题。

**Comment by emmpp** [comment]
是那个分支管这个啊？

**Comment by UjuiUjuMandan** [comment]
@emmpp 
这，不是有人提了么？
https://github.com/FooIbar/EhViewer/issues/161 。

**Comment by emmpp** [comment]
哦哦犯蠢了
