### ISSUE TITLE
刷新时不能直接到顶部而需要重新划上去

### ISSUE THREAD

**Issue by emmpp** [UjuiUjuMandan/EhViewer#16]
### 复现步骤 / Step to reproduce

刷新不能到顶部

### 预期行为 / Expected behaviour

![Screenshot_20231031_193803](https://github.com/UjuiUjuMandan/EhViewer/assets/149444278/8e22caae-8f22-4c28-bef2-cd169098a3ff)

### 实际行为 / Actual Behaviour

![Screenshot_20231031_193803](https://github.com/UjuiUjuMandan/EhViewer/assets/149444278/3f6ab26b-30e6-40ec-9519-bc76ff24f847)
需要重新上划

### 应用日志 / App logs

希望能够优化

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.8.11.0

### EhViewer CI 版本 / EhViewer CI Version

3d5c3a6

### Android 系统版本 / Android version

miui12.5

### 设备型号 / Device model

xiaomi12

### SoC 型号 / Soc model

骁龙8

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
本分支不处理这些问题。
