### ISSUE TITLE
能否恢复首页左滑功能呢？

### ISSUE THREAD

**Issue by jatalins** [UjuiUjuMandan/EhViewer#17]
### 复现步骤 / Step to reproduce

首页左滑打开快速搜索栏

### 预期行为 / Expected behaviour

问过上游，他删掉首页左右划以后好像暂时没有计划改回来，搜索记录，发现首页右滑打开菜单本分支已经恢复，左滑的快速搜索能不能也恢复呢？如果有人怕误触，设置里加个开关应该也行吧，盼望回复谢谢

### 实际行为 / Actual Behaviour

![Screenshot_20231103_135609](https://github.com/UjuiUjuMandan/EhViewer/assets/85802085/3fef3fed-e210-4e5f-aa4c-5c1e687b730a)

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1.cc

### EhViewer CI 版本 / EhViewer CI Version

5a2e5d7

### Android 系统版本 / Android version

harmony4.0

### 设备型号 / Device model

mate30

### SoC 型号 / Soc model

kirin990

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
> 不接受和直连无关的功能请求。
