### ISSUE TITLE
闪退问题。。。想请问一下大佬的这个分支怎么使用啊，我下了v8a版本的apk但点不进应用TAT，不太会哦

### ISSUE THREAD

**Issue by eleven0806** [UjuiUjuMandan/EhViewer#19]
### 复现步骤 / Step to reproduce

闪退

### 预期行为 / Expected behaviour

启动应用

### 实际行为 / Actual Behaviour

闪退无法进入

### 应用日志 / App logs

如题

### 浏览站点 / Browsing site

无

### EhViewer 版本号 / EhViewer version code

1.8.11.1-cc

### EhViewer CI 版本 / EhViewer CI Version

42297a3

### Android 系统版本 / Android version

MIUI14.0.3

### 设备型号 / Device model

xiaomi10

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by eleven0806** [comment]
是刚接触，不是太懂，所以问问，麻烦大佬了TAT

**Comment by eleven0806** [comment]
嗷嗷，会了会了，不好意思直接下了CC的版本没有先下上游的安装包再更新，现在明白了，麻烦了麻烦了，希望不会再有跟我一样傻的哥们😂😂

**Comment by UjuiUjuMandan** [comment]
你不需要先下上游的安装包再更新的。

**Comment by eleven0806** [comment]
嘶，这样吗，看来不是顺序问题，那就没搞明白为啥会闪退了，我得再试试，难不成是巧合？

**Comment by UjuiUjuMandan** [comment]
人呢？

**Comment by eleven0806** [comment]
不好意思，忘记反馈了，在小米12S上再次进行了尝试，在下载v8a的安装包后依旧出现了闪退，且这回下载上游再更新cc版本后依旧闪退，我的能力不足以解析软件出了什么问题，只能报告一下表象TAT

**Comment by UjuiUjuMandan** [comment]
@eleven0806 https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6762445362

这个呢？

**Comment by Pantyhose-X** [comment]
> 人呢？

为什么 releases 链接是apk [EhViewer-1.8.11.1-cc-default-arm64-v8a.apk](https://github.com/UjuiUjuMandan/EhViewer/releases/download/1.8.11.1-cc/EhViewer-1.8.11.1-cc-default-arm64-v8a.apk) 下载下来的却是zip 不是apk  我是不是被劫持了？
