### ISSUE TITLE
Display Sad Panda

### ISSUE THREAD

**Issue by UjuiUjuMandan** [UjuiUjuMandan/EhViewer#2]
此处应该显示“Sad Panda”来提示用户其没有权限，而不是显示如上所述的内容。

_Originally posted by @UjuiUjuMandan in https://github.com/UjuiUjuMandan/EhViewer/issues/1#issuecomment-1754208245_

**Comment by iiikunn** [comment]
![Uploading Screenshot_2023-10-10-10-26-17-193_moe.tarsin.ehviewer.jpg…]()
感谢。
我的账号似乎是有权限的。在更新您的版本之前，我使用上一位维护者的版本，似乎没有出现过类似的问题。

**Comment by iiikunn** [comment]
![Screenshot_2023-10-10-10-26-17-193_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/144868657/daedba8e-fea1-4d89-ad1a-f0c0070b4785)
感谢。
我的账号似乎是有权限的。在更新您的版本之前，我使用上一位维护者的版本，似乎没有出现过类似的问题。

**Comment by iiikunn** [comment]
浏览器也是可以正常访问的。
![Screenshot_2023-10-10-10-30-35-314_com mmbox xbrowser pro](https://github.com/UjuiUjuMandan/EhViewer/assets/144868657/b90db9e4-9673-46a8-a453-4eb7b428d7fb)

**Comment by iiikunn** [comment]
感谢。我想起来了，在上一位维护者的版本似乎也有这种问题，切换网络后提示sad panda
同样也是稍后即可恢复。

**Comment by UjuiUjuMandan** [comment]
> 。 我的账号似乎是有权限的。在更新您的版本之前，我使用上一位维护者的版本，似乎没有出现过类似的问题。

是的，这是刚才我顺便看到的问题，与您无关。留个记录而已。

**Comment by iiikunn** [comment]
> > 我的账号似乎是有权限的。在更新您的版本之前，我使用上一位维护者的版本，似乎没有出现过类似的问题。
> 
> 是的，这是刚才我顺便看到的问题，与您无关。留个记录而已。

感谢。如果需要更多信息可以随时询问。
