### ISSUE TITLE
无法连接，显示java.net.protocolexception

### ISSUE THREAD

**Issue by kyonkoo** [UjuiUjuMandan/EhViewer#23]
### 复现步骤 / Step to reproduce

![Screenshot_20231126_234307](https://github.com/UjuiUjuMandan/EhViewer/assets/3982226/abce29d4-c7d3-428b-b3b2-71154bf584d3)
开启Quic支持（无论是否开clash vpn）则出现上述提醒，无法连接。

关闭Quic支持，则显示network error，同样无法连接，总之就是现在怎么也用不了

### 预期行为 / Expected behaviour

如上所述

### 实际行为 / Actual Behaviour

如上所述

### 应用日志 / App logs

[log-2023-11-26-23-43-31-045.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13467312/log-2023-11-26-23-43-31-045.zip)

### 备注 / Addition details

问题出现在换机后，我用vivo自带的换机app迁移到新机之后便再也无法正常使用。之前在旧机同样的网络环境下使用一切正常。旧版本和最新版本app、旧版本和最新版本手机系统均无影响。

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1-cc

### EhViewer CI 版本 / EhViewer CI Version

c13b2d5

### Android 系统版本 / Android version

Vivo OriginOS4

### 设备型号 / Device model

Vivo x100

### SoC 型号 / Soc model

天玑9300

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
我没有 vivo 的换机 app ，无法复现。我推荐的迁移方式是通过手动拷贝下载文件夹和导出 - 导入数据。
