### ISSUE TITLE
收藏中搜索功能不起作用

### ISSUE THREAD

**Issue by emmpp** [UjuiUjuMandan/EhViewer#25]
### 复现步骤 / Step to reproduce

在收藏中搜索时不会显示对应内容且滑动是会变回最开始界面

### 预期行为 / Expected behaviour

出现问题

### 实际行为 / Actual Behaviour

https://github.com/UjuiUjuMandan/EhViewer/assets/149444278/4a5db1be-8742-4fe4-b082-5dbc800233dc

### 应用日志 / App logs

无

### 备注 / Addition details

希望解决

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.9.0

### EhViewer CI 版本 / EhViewer CI Version

c70960c

### Android 系统版本 / Android version

13

### 设备型号 / Device model

iqoo9

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/491
