### ISSUE TITLE
联想Y700 2023平板 上闪退

### ISSUE THREAD

**Issue by liveviiv** [UjuiUjuMandan/EhViewer#26]
### 复现步骤 / Step to reproduce

使用EhViewer-1.9.0-cc-default-arm64-v8a.apk 版本 。
安装后点图标运行就闪退了

### 预期行为 / Expected behaviour

正常运行

### 实际行为 / Actual Behaviour

无法运行

### 应用日志 / App logs

无法运行程序导出日志

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

EhViewer-1.9.0-cc-default-arm64-v8a.apk

### EhViewer CI 版本 / EhViewer CI Version

EhViewer-1.9.0-cc-default-arm64-v8a.apk

### Android 系统版本 / Android version

zui 15.0.677

### 设备型号 / Device model

联想Y700 2023

### SoC 型号 / Soc model

高通 8gen1

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Kuma15781** [comment]
尝试在开启WLAN的状态下打开应用
我联想pad2022 ZUI14也是这个状况
断网开启应用闪退
我的版本还是1.8.11.1-cc 还在等新版本的稳定性观察

你可以测试下上游的最新版本断网闪不闪退
如果闪退就是上游的问题  如果不闪退就是这个直连版本的问题
上游 https://github.com/FooIbar/EhViewer

**Comment by Kuma15781** [comment]
这新版Y700我也在盯着呢...
如果能用的话麻烦回个信 我怕明年买回来后不能用。。
