### ISSUE TITLE
使用没多久就崩溃了，经常这样，出1.10.0版本了，求更新，谢谢

### ISSUE THREAD

**Issue by SAF-503** [UjuiUjuMandan/EhViewer#27]
### 复现步骤 / Step to reproduce

打开APP使用一小时左右就会随机出现

### 预期行为 / Expected behaviour

![Screenshot_20231214-232931](https://github.com/UjuiUjuMandan/EhViewer/assets/49642277/43663268-cdba-4376-99c6-c2989bf55e08)

### 实际行为 / Actual Behaviour

![Screenshot_20231214-232931](https://github.com/UjuiUjuMandan/EhViewer/assets/49642277/61f2a19b-7bbb-46c1-8d1d-54fdb76c7d00)

### 应用日志 / App logs

[log-2023-12-14-23-32-14-162.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13675255/log-2023-12-14-23-32-14-162.zip)

### 备注 / Addition details

使用没多久就崩溃了，经常这样，

出1.10.0版本了，求更新，谢谢

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.9

### EhViewer CI 版本 / EhViewer CI Version

62f966c

### Android 系统版本 / Android version

9

### 设备型号 / Device model

雷电模拟器9

### SoC 型号 / Soc model

雷电模拟器9

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
#1
