### ISSUE TITLE
缩略图能正常加载，点进去阅读就加载不了了

### ISSUE THREAD

**Issue by 1429886467** [UjuiUjuMandan/EhViewer#29]
### 复现步骤 / Step to reproduce

https://github.com/UjuiUjuMandan/EhViewer/assets/107488796/5bad4e23-9b96-42f8-a26d-ecb5ba1cd008

### 预期行为 / Expected behaviour

应该正常加载

### 实际行为 / Actual Behaviour

实际加载不出来
![Screenshot_2023-12-18-01-21-22-011_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/107488796/651ce043-6e69-4b0e-97bf-5715cf6aaa30)

### 应用日志 / App logs

[log-2023-12-18-01-22-19-258.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13697157/log-2023-12-18-01-22-19-258.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.0-cc

### EhViewer CI 版本 / EhViewer CI Version

47b5b08

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

小米12s

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Kariru** [comment]
我还以为是我的问题，原来都这样。。

**Comment by 1429886467** [comment]
> 我还以为是我的问题，原来都这样。。

贴吧有解决方法，但是我试了没用，上游的foolbar的1.10版本也因为重大bug删了，不知道是不是上游的问题

**Comment by Kariru** [comment]
> > 我还以为是我的问题，原来都这样。。
> 
> 贴吧有解决方法，但是我试了没用，上游的foolbar的1.10版本也因为重大bug删了，不知道是不是上游的问题

应该是上游问题，我用其他两个都是正常的

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/508#issuecomment-1858919509

**Comment by 1429886467** [comment]
果然是上游的问题啊

**Comment by UjuiUjuMandan** [comment]
@1429886467 @Kariru 我已经合并了上游的修复，在下一个版本发布之前可以暂时用这个：https://github.com/UjuiUjuMandan/EhViewer/actions/runs/7240229113 。

**Comment by 1429886467** [comment]
> @1429886467 @Kariru 我已经合并了上游的修复，在下一个版本发布之前可以暂时用这个：[https://github.com/UjuiUjuMandan/EhViewer/actions/runs/7240229113< /span>](https://github.com/UjuiUjuMandan/EhViewer/actions/runs/7240229113) 。

感谢大佬😇
