### ISSUE TITLE
使用VPN连接里站后切换回直连显示奇怪的错误

### ISSUE THREAD

**Issue by KurosukeX** [UjuiUjuMandan/EhViewer#3]
### 复现步骤 / Step to reproduce

1.直连进入里站，正常访问
2.连接VPN后刷新并访问画廊，正常访问
3.关闭VPN后重启软件，显示奇怪的错误，切换到表站正常访问
4.使用以上步骤复现表站亦显示奇怪的错误
4.删除data/data/moe.tarsin.ehviewer/cache/http_cache/prefs/local_prefs.json后重启软件直连进入，表里站正常访问

### 预期行为 / Expected behaviour

直连

### 实际行为 / Actual Behaviour

显示奇怪的错误

### 应用日志 / App logs

[logcat-2023-10-12-13-55-17-976.txt](https://github.com/UjuiUjuMandan/EhViewer/files/12877698/logcat-2023-10-12-13-55-17-976.txt)

### 备注 / Addition details

导致“奇怪的错误”出现的local_pref.json文件如下，删除后直连正常访问
[local_prefs.json](https://github.com/UjuiUjuMandan/EhViewer/files/12877732/local_prefs.json)

### EhViewer 版本号 / EhViewer version code

1.8.9.7-censorcircum

### EhViewer CI 版本 / EhViewer CI Version

8e8706b

### Android 系统版本 / Android version

Android 11

### 设备型号 / Device model

Xperia 1 II

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
看起来似乎是，只要一连接VPN就会缓存错误的 DNS 结果到某文件。

1. 你的 VPN 是否有分应用代理功能，将 EhViewer 加入试试能否解决问题。
2. 正常直连时 local_pref.json 内容为何？

**Comment by KurosukeX** [comment]
换用了clash.meta后就不会出现奇怪的错误了，local_prefs.json也没有变化，大感谢
之前用的vpn是西部世界
