### ISSUE TITLE
有的本子在这个版本打不开

### ISSUE THREAD

**Issue by mgcccc** [UjuiUjuMandan/EhViewer#31]
### 复现步骤 / Step to reproduce

有的本子在这个版本打不开，在别的版本能打开并加载

### 预期行为 / Expected behaviour

它应该进入加载图片的页面

### 实际行为 / Actual Behaviour

它变成黑屏

### 应用日志 / App logs

日志文件缓存了提交不了

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.1-cc

### EhViewer CI 版本 / EhViewer CI Version

762a8ca

### Android 系统版本 / Android version

magicos7.1

### 设备型号 / Device model

honor magic5pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
请问是和 #30 一样的情况吗？解决了吗？
