### ISSUE TITLE
直连eh报错

### ISSUE THREAD

**Issue by ailerfa** [UjuiUjuMandan/EhViewer#32]
### 复现步骤 / Step to reproduce

安装最新的cc版本打开后出现此问题

### 预期行为 / Expected behaviour

直连应该直接显示

### 实际行为 / Actual Behaviour

![Screenshot_20231225-224846_EhViewer](https://github.com/UjuiUjuMandan/EhViewer/assets/74477673/5e3f0c58-7997-4191-bc35-4d8631a91d33)

如图所示

### 应用日志 / App logs

[log-2023-12-25-22-51-23-231.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13766523/log-2023-12-25-22-51-23-231.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

EhViewer-1.10.1-cc-default-arm64-v8a

### EhViewer CI 版本 / EhViewer CI Version

762a7ca

### Android 系统版本 / Android version

Android10

### 设备型号 / Device model

Galaxy S20 Ultra 5G

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by ailerfa** [comment]
> 可能与 #1 是相同的情况，尝试重启应用即可。

尝试重启没有效果，依旧是挂上梯子才能显示

**Comment by ailerfa** [comment]
`补充，不知什么原因，在切换至ehentai再切换回ex后能够正常加载

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer/issues/20#issuecomment-1806993177
