### ISSUE TITLE
批量操作本地收藏转云端收藏失败导致本地收藏消失，云端收藏只有部分

### ISSUE THREAD

**Issue by wdawdaw454** [UjuiUjuMandan/EhViewer#33]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.为本地收藏添加1000+个内容
![QQ图片20231230193623](https://github.com/UjuiUjuMandan/EhViewer/assets/87644184/59d74323-8faa-41e0-bb0c-25194d9ab15c)

2.一次性选中所有内容，将本地收藏内容批量移动到云端收藏夹Favorites 9
![D327DDC05C990806527500BB8DE78F58](https://github.com/UjuiUjuMandan/EhViewer/assets/87644184/35228566-690a-4631-b14a-d19cd828cabd)

3.本地收藏夹内容快速被删除，然后云端收藏夹Favorites 9内容缓慢增加，最后停下，转移内容缺失
![5EFD4FF20E69821C5F5DC58DCE4C4478](https://github.com/UjuiUjuMandan/EhViewer/assets/87644184/b78dfd15-2473-4bd7-9b2f-cb90f3e779a7)

### 预期行为 / Expected behaviour

云端收藏夹Favorites 9应该有1128个内容

### 实际行为 / Actual Behaviour

云端收藏夹Favorites 9文件夹内容远小于1128个，转移内容缺失

### 应用日志 / App logs

[log-2023-12-30-19-43-54-147.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13797899/log-2023-12-30-19-43-54-147.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.1-cc

### EhViewer CI 版本 / EhViewer CI Version

762a7ca

### Android 系统版本 / Android version

MIUI14.0.7

### 设备型号 / Device model

redmi 40s

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
我不知道这部分是什么...建议找 FooIBar 提。
