### ISSUE TITLE
更新后，搜索汉化画廊不能显示缩略图

### ISSUE THREAD

**Issue by laowanglr** [UjuiUjuMandan/EhViewer#34]
### 复现步骤 / Step to reproduce

一些可以显示是在未添加汉化标签后在首页加载出现，缓存未清理

### 预期行为 / Expected behaviour

应该可以正常显示封面图

### 实际行为 / Actual Behaviour

实际上添加汉化标签搜索后，不能如1.08.1.1正常显示画廊封面

### 应用日志 / App logs

[Uploading log-2024-01-01-22-26-57-418.zip…]()

### 备注 / Addition details

高级设置设定为：绕过vpn关闭，内置hosts开启

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.2-cc

### EhViewer CI 版本 / EhViewer CI Version

078a1fd

### Android 系统版本 / Android version

miui17

### 设备型号 / Device model

xiaomi14

### SoC 型号 / Soc model

8gen3

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by laowanglr** [comment]
Uploading Screenrecorder-2024-01-01-22-31-37-22.mp4…

**Comment by UjuiUjuMandan** [comment]
🤔 怎么解决的？
