### ISSUE TITLE
Exhentai直连浏览&下载缓慢，大概有60%概率出错

### ISSUE THREAD

**Issue by pokemonzwy** [UjuiUjuMandan/EhViewer#35]
### 复现步骤 / Step to reproduce

不能稳定复现。

### 预期行为 / Expected behaviour

照理来说应该正常浏览。

### 实际行为 / Actual Behaviour

![Uploading Screenshot_20240102_191726_edit_401941229909802.jpg…]()
![Screenshot_20240103_163044](https://github.com/UjuiUjuMandan/EhViewer/assets/55735944/ad00f775-e490-485a-bf5c-7ac72750a226)

### 应用日志 / App logs

[log-2024-01-03-16-31-04-910.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13817097/log-2024-01-03-16-31-04-910.zip)
[log-2024-01-03-16-42-27-801.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13817099/log-2024-01-03-16-42-27-801.zip)

### 备注 / Addition details

不好意思啊大佬，很感谢您对直连功能的改进，现在我更新版本之后碰到了点问题想问问。
当初网站设置调整，我一开始下载了您最老的那个版本，那个时候一切还都没出问题。
但是自从更新版本后，时不时就跳出截图显示的流泪安卓机器人，而且下载速度动不动就掉到0B/S，在此基础上通过软件内部更新了您2023.12.31发布的最新版本这个问题依旧没有得到解决。
弱弱地多问一句，话说同步上游安装啥的应该不是指要下载Follbar对应的版本再下载您这个覆盖安装吧。
我另外又下载了绿E，在同一时间段彩E连接失败的情况下绿E并未受到影响。现在我这彩E就处在时好时坏的状态，由于彩E可自由拖拽下载文件顺序，以及配额制后消耗速度似乎也低于绿E，我还是比较希望彩E能正常使用。目前我确定彩E并未被手机系统管控，WiFi和流量都是许可使用，家里网络运营商是电信。
这个应该是直连的问题吧，麻烦您看看我这到底是什么问题，万分感谢！

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.0-cc

### EhViewer CI 版本 / EhViewer CI Version

078a1fd

### Android 系统版本 / Android version

magic ui 6.1.0.127(C00E122R8P9patch01)

### 设备型号 / Device model

荣耀X20  NTN-AN20

### SoC 型号 / Soc model

Media Tek MT6877 5G

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
流泪安卓机器人不是关键，你确定每次出现的错误都是 ERR_ADDRESS_UNREACHABLE 吗？

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer/issues/20#issuecomment-1806993177

**Comment by pokemonzwy** [comment]
ERR_CONNECTION和ERR_ADDRESS都有。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UjuiUjuMandan/EhViewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 晚上6:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UjuiUjuMandan/EhViewer] Exhentai直连浏览&amp;下载缓慢，大概有60%概率出错 (Issue #35)





 
流泪安卓机器人不是关键，你确定每次出现的错误都是 ERR_ADDRESS_UNREACHABLE 吗？
