### ISSUE TITLE
无法输入任何内容

### ISSUE THREAD

**Issue by dqt-12** [UjuiUjuMandan/EhViewer#37]
### 复现步骤 / Step to reproduce

github重新安装，EhViewer-1.10.2.2-cc-default-universal

### 预期行为 / Expected behaviour

登录界面能输入账号、密码，cookie等。
搜索栏能输入

### 实际行为 / Actual Behaviour

登录界面账号、密码、cookie等所有的地方都无法输入。只能点击界面上的“从剪切板导入”。
搜索栏无法输入任何文字，回车也没反应。
该app对输入法没有任何回应。

### 应用日志 / App logs

[log-2024-01-04-09-07-36-473.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13836463/log-2024-01-04-09-07-36-473.zip)

### 备注 / Addition details

还有屏幕闪烁

### 浏览站点 / Browsing site

E-Hentai 和 ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2.2

### EhViewer CI 版本 / EhViewer CI Version

5123be2

### Android 系统版本 / Android version

鸿蒙3

### 设备型号 / Device model

华为 mate30 5G

### SoC 型号 / Soc model

麒麟990 5G

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/601
