### ISSUE TITLE
直连只能看封面和预览

### ISSUE THREAD

**Issue by yeyansanren** [UjuiUjuMandan/EhViewer#38]
### 复现步骤 / Step to reproduce

重装几次了

### 预期行为 / Expected behaviour

rt

### 实际行为 / Actual Behaviour

rt

### 应用日志 / App logs

[log-2024-01-06-03-03-33-639.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13845625/log-2024-01-06-03-03-33-639.zip)

### 浏览站点 / Browsing site

两个都试过

### EhViewer 版本号 / EhViewer version code

1.10.2.2-cc

### EhViewer CI 版本 / EhViewer CI Version

5123be2

### Android 系统版本 / Android version

MIUI 13.0.10

### 设备型号 / Device model

REDMI note9pro

### SoC 型号 / Soc model

忘了

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by yeyansanren** [comment]
正文转半天然后网络错误

**Comment by yeyansanren** [comment]
贴吧看了一眼，出这个问题的好像都是江苏ip，那没事了

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer/issues/30#issuecomment-1878925486

**Comment by yeyansanren** [comment]
> [#30 (comment)](https://github.com/UjuiUjuMandan/EhViewer/issues/30#issuecomment-1878925486)

那些操作都试过啦，没用喵，运营商劫持是这样的

**Comment by yeyansanren** [comment]
> [#30 (comment)](https://github.com/UjuiUjuMandan/EhViewer/issues/30#issuecomment-1878925486)

我尝试了一下，找到解决方法了。路由器上网设置自动配置DNS改为手动配置，114.114.115.115，这样直连就可以加载出正文图片。我来回切了一次确认我这样可以解决，不知道别人行不行。
