### ISSUE TITLE
QUIC 直连一直超时

### ISSUE THREAD

**Issue by Pony-CW** [UjuiUjuMandan/EhViewer#4]
### 复现步骤 / Step to reproduce

0.清除缓存，不想重装（确信）
1.打开软件

### 预期行为 / Expected behaviour

直连

### 实际行为 / Actual Behaviour

超时

### 应用日志 / App logs

重新上传
![logcat-2023-10-20-04-52-00-898.txt](https://github.com/UjuiUjuMandan/EhViewer/files/13047713/logcat-2023-10-20-04-52-00-898.txt)

### 备注 / Addition details

无论有没有 GMS

### EhViewer 版本号 / EhViewer version code

1.8.10.0-censorcircum (Releases)

### EhViewer CI 版本 / EhViewer CI Version

3c4553f

### Android 系统版本 / Android version

ColorOS 13.1 PGZ110_13.1.0.182(CN01) / Android 13

### 设备型号 / Device model

一加 Ace 竞速版 / OnePlus Ace Racing Edition / PGZ110

### SoC 型号 / Soc model

天玑 8100-MAX / Dimensity 8100-MAX

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 1183807453** [comment]
一直显示超时，或者是网络错误，切换Cloudfare IP 没有效果，用电脑浏览器QUIC显示ERR_QUIC_PROTOCOL_ERROR

**Comment by UjuiUjuMandan** [comment]
文件里 logcat 是空的，麻烦重新复现后上传日志。

**Comment by 1183807453** [comment]
您好，您的邮件我已经收到。看到邮件后，我会尽快给您回复。                                                          胡广

**Comment by Pony-CW** [comment]
> 文件里 logcat 是空的，麻烦重新复现后上传日志。

不好意思，开发者功能里的日志缓冲区关了😂，已重新上传有内容的日志

**Comment by UjuiUjuMandan** [comment]
看起来是 cronet 根本没启用。
@Pony-CW 我把判断是否可用的条件都删了，你试试这个版本: https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6580428301 。

**Comment by Pony-CW** [comment]
> 看起来是 cronet 根本没启用。
> @Pony-CW 我把判断是否可用的条件都删了，你试试这个版本: https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6580428301 。

这个没问题了

顺便问个题外话，之前其实看了看 commit，咋又把Google Play Service（com.google.android.gms.common.api.GoogleApiActivity）加回来了呢😂

**Comment by UjuiUjuMandan** [comment]
> 咋又把Google Play Service（com.google.android.gms.common.api.GoogleApiActivity）加回来了呢😂

因为我想利用 play 服务一下，没它的话再用内置的。

**Comment by Pony-CW** [comment]
> 因为我想利用 play 服务一下，没它的话再用内置的。

噢…其实之前就在用 bdfbd35 这个 ci（现在提交里找不到了），然后后脚就接着跟你这个加回 play 和其他接着的 ci
然后直连挂了，当时也没说🫠

**Comment by Pony-CW** [comment]
辛苦了
