### ISSUE TITLE
快速点按进度条跳转到第一页大概率失效

### ISSUE THREAD

**Issue by NoroHime** [UjuiUjuMandan/EhViewer#40]
### 复现步骤 / Step to reproduce

点开含有进度条记录的画廊，快速点按到第一页实际没有跳转

### 预期行为 / Expected behaviour

图片跳转到第一页

### 实际行为 / Actual Behaviour

没有跳转

### 应用日志 / App logs

-

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.2.4

### EhViewer CI 版本 / EhViewer CI Version

-

### Android 系统版本 / Android version

-

### 设备型号 / Device model

-

### SoC 型号 / Soc model

-

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by NoroHime** [comment]
最后一段日志
`1-07 01:54:52.705 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.705 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.705 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.706 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.706 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.706 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.727 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.727 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.727 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.727 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.727 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.727 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.737 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.737 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.737 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.739 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.739 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.739 16482 16482 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
01-07 01:54:52.751 16482 16482 I Quality : ActivityThread: activityStart delay 64 moe.tarsin.ehviewer 16482
01-07 01:54:52.753 16482 16482 D WindowManager: Add to mViews: DecorView@3104dc0[ReaderActivity],pkg= moe.tarsin.ehviewer
01-07 01:54:52.761 16482 16482 I Quality : Skipped: false 6 cost 73.898766 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:52.777 16482 16482 V OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 3120 getDecorView.51400128
01-07 01:54:52.787 16482 18090 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
01-07 01:54:52.796 16482 16482 D ei0     : setChaptersInternal
01-07 01:54:52.796 16482 16482 D ei0     : Pager first layout
01-07 01:54:52.796 16482 16482 D ei0     : moveToPage 20
01-07 01:54:52.799 16482 16482 I Quality : Skipped: false 3 cost 34.279007 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:52.804 16482 22668 D Qk1     : Directory lookup cache created for 画廊文件夹名称
01-07 01:54:52.820 16482 16482 I Quality : Skipped: false 1 cost 11.225712 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:52.841 16482 16529 W System.err: ig0: I71 was cancelled; job=I71{Cancelling}@64ad050
01-07 01:54:52.851 16482 22668 W System.err: ig0: I71 was cancelled; job=I71{Cancelling}@8e9aa27
01-07 01:54:52.851 16482 22683 W System.err: ig0: I71 was cancelled; job=I71{Cancelling}@6bc567d
01-07 01:54:52.870 16482 22683 W System.err: ig0: I71 was cancelled; job=I71{Cancelling}@867d143
01-07 01:54:53.000 16482 16523 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
01-07 01:54:53.000 16482 16523 D OpenGLRenderer: endAllActiveAnimators on 0xb4000076c05ce600 (Rm1) with handle 0xb40000764d57c720
01-07 01:54:55.862 16482 16482 D Activity: dispatchKeyEvent to eu.kanade.tachiyomi.ui.reader.ReaderActivity@6adb440 will call onBackPressed
01-07 01:54:55.862 16482 16482 D Activity: eu.kanade.tachiyomi.ui.reader.ReaderActivity@6adb440onBackPressed!
01-07 01:54:55.892 16482 16482 D OplusInputMethodUtil: imm dynamicallyConfigDebugByDumpArgs []
01-07 01:54:55.924 16482 16482 I Quality : Skipped: true 1 cost 20.17524 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:55.928 16482 16500 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
01-07 01:54:56.153 16482 16523 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
01-07 01:54:56.181 16482 16482 D OplusScrollToTopManager: unregisterGuidePopupDismissReceiverInSystemUI
01-07 01:54:56.181 16482 16482 D OplusScrollToTopManager: Receiver not registered: android.view.OplusScrollToTopManager$1@fe2cdd8
01-07 01:54:56.181 16482 16482 D OplusScrollToTopManager: unregisterSystemUIBroadcastReceiver 
01-07 01:54:56.181 16482 16482 D OplusScrollToTopManager: java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@b59a531
01-07 01:54:56.182 16482 16482 V OplusZoomWindowDecorViewHelper: removeZoomView
01-07 01:54:56.197 16482 16482 I Quality : Skipped: false 2 cost 25.796265 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:56.492 16482 16482 I Quality : Skipped: false 1 cost 20.699312 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:56.528 16482 16482 I Quality : Skipped: false 3 cost 34.446064 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:56.567 16482 16482 I Quality : Skipped: false 2 cost 28.517328 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:56.587 16482 16482 I Quality : Skipped: false 1 cost 15.638543 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:57.185 16482 16482 I Quality : Skipped: false 1 cost 12.223732 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:57.209 16482 16482 I Quality : Skipped: false 1 cost 13.814392 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:54:58.170 16482 16482 I Quality : Skipped: false 5 cost 63.016754 refreshRate 0 processName moe.tarsin.ehviewer
01-07 01:55:00.514 16482 16523 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
01-07 01:55:00.514 16482 16523 D OpenGLRenderer: endAllActiveAnimators on 0xb400007652184000 (Rm1) with handle 0xb400007648560180
01-07 01:55:01.889 16482 16482 D WindowManager: Add to mViews: DecorView@1481f26[MainActivity],pkg= moe.tarsin.ehviewer`

**Comment by UjuiUjuMandan** [comment]
没听懂。建议重新描述或者录屏。

**Comment by NoroHime** [comment]
> 没听懂。建议重新描述或者录屏。

几乎稳定重现问题

**Comment by NoroHime** [comment]
> 没听懂。建议重新描述或者录屏。

https://github.com/UjuiUjuMandan/EhViewer/assets/25362335/88e097ac-16b0-431e-9b7e-5f0db3ecb962

几乎稳定重现问题

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/614
