### ISSUE TITLE
无法直连

### ISSUE THREAD

**Issue by a845542683** [UjuiUjuMandan/EhViewer#41]
### 复现步骤 / Step to reproduce

更新1.10.2.4-cc（dd6be00）之后，无法直连，显示网络错误，vpn下显示sad panda

### 预期行为 / Expected behaviour

7777777777777777777

### 实际行为 / Actual Behaviour

77777777 7  

### 应用日志 / App logs

7777777  77           

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

zzz

### EhViewer CI 版本 / EhViewer CI Version

zzzz

### Android 系统版本 / Android version

zzzzzz

### 设备型号 / Device model

红米k60

### SoC 型号 / Soc model

77777

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
网络错误信息过少，无法复现。
Sad Panda 从来不是应用的问题。
