### ISSUE TITLE
无法直连ex画廊

### ISSUE THREAD

**Issue by a845542683** [UjuiUjuMandan/EhViewer#42]
### 复现步骤 / Step to reproduce

今天早上开始sad panda，更新之后依然如此，切换eh画廊之后可以正常使用，但切换回ex画廊站点之后便sad panda

### 预期行为 / Expected behaviour

ex无法正常使用

### 实际行为 / Actual Behaviour

![Screenshot_2024-01-07-08-44-03-559_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/22552660/9b3e970c-38a1-4df8-a4a9-85c0c99e42ba)

### 应用日志 / App logs

[log-2024-01-07-08-44-24-661.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13851792/log-2024-01-07-08-44-24-661.zip)

### 浏览站点 / Browsing site

eh正常使用，ex无法使用

### EhViewer 版本号 / EhViewer version code

1.10.2.4-cc

### EhViewer CI 版本 / EhViewer CI Version

dd6be00

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

红米k60

### SoC 型号 / Soc model

不知

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
Sad Panda是连接上了，网站给你了空回复而已，这不是应用的问题。

**Comment by UjuiUjuMandan** [comment]
关于怎么获取 exhentai 权限，建议读这篇条目的延伸阅读的文章。
https://zh.wikibooks.org/wiki/EhViewer 。

**Comment by UjuiUjuMandan** [comment]
哦对了，你之前是可以看 exhentai ，然后突然不可以了是吧，我猜测是网站收回权限了吧，或者 cookie 失效了？

还记得你账号注册时用的哪个地区的IP吗？尝试用那个地区的梯子重新登录，看能不能获取到 cookie 。

**Comment by mj17shAlice** [comment]
我也遇到了这个情况，确实是cookie的问题
刚刚看了眼，ipb_member_id、ipb_pass_hash和igneous值都变了
