### ISSUE TITLE
看不到本子 显示网络错误 已启用VPN

### ISSUE THREAD

**Issue by Lununz** [UjuiUjuMandan/EhViewer#43]
### 复现步骤 / Step to reproduce

开启VPN（已指定eh加速）
打开eh
显示 网络错误
打开收藏
显示 网络错误
打开 设置 eh ehentai设置 正常显示设置页面
[

https://github.com/UjuiUjuMandan/EhViewer/assets/133779833/5965d2e9-e8ef-4b1d-b4ab-e9bf1226d284

](url)

### 预期行为 / Expected behaviour

他应该是正常显示出画廊（绿eh一切正常）

### 实际行为 / Actual Behaviour

显示网络错误 

### 应用日志 / App logs

[log-2024-01-12-19-56-58-436.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13918805/log-2024-01-12-19-56-58-436.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.2.4-cc

### EhViewer CI 版本 / EhViewer CI Version

dd6be00

### Android 系统版本 / Android version

miui 13.0.10 稳定版

### 设备型号 / Device model

红米 k50 ultra

### SoC 型号 / Soc model

骁龙8+ 移动平台

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
开VPN用这个干嘛？不读首页README吗？
