### ISSUE TITLE
1.10.3-cc版本闪退

### ISSUE THREAD

**Issue by yinyingweimu** [UjuiUjuMandan/EhViewer#46]
### 复现步骤 / Step to reproduce

在github上更新1.10.3-cc-default-arm64-v8a.apk最新版本后软件闪退

### 预期行为 / Expected behaviour

正常登录

### 实际行为 / Actual Behaviour

如果下载1.10.3-cc-marshmallow-arm64-v8a.apk这个可以正常登录，但没有覆盖原来的软件而是多出来一个新的ehviewer,也没有原来的ehviewer的本地收藏和浏览记录
![微信图片_20240222011157](https://github.com/UjuiUjuMandan/EhViewer/assets/160767045/3c47a016-d084-4d9f-8400-cf28b9102ab0)
![微信图片_20240222011211](https://github.com/UjuiUjuMandan/EhViewer/assets/160767045/c44e7403-443d-41e0-8fcf-8349a8020589)

### 应用日志 / App logs

无

### 备注 / Addition details

 想问一下我是要等下一次更新覆盖原来的软件就行,还是要手动把本地收藏和浏览记录的文件导入到另一个ehviewer里？如果要导入的话可以麻烦给一下本地收藏和浏览记录的缓存文件的存储路径，以及指导一下怎么转移吗，实在真的不想本地收藏就这么没了......

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.3-cc

### EhViewer CI 版本 / EhViewer CI Version

1

### Android 系统版本 / Android version

1

### 设备型号 / Device model

vivox60 v2046A

### SoC 型号 / Soc model

1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by yinyingweimu** [comment]
试了很多遍了，实在没找到办法，连夜注册了github来问，要是本地收藏真的没法找回了我都不敢想我会失去多少本子💔或许此生再也没什么悲喜了💔

**Comment by yinyingweimu** [comment]
还有我能找到Android/data/moe.tarsin.ehviewer/files/download这个路径，里面确实有我下载的漫画，但是没有其他的文件了

**Comment by UjuiUjuMandan** [comment]
1. Android 版本是？

2. 是从“最新 CI 版本降级到稳定版本”吗？（ https://github.com/FooIbar/EhViewer/issues/759 ）

**Comment by yinyingweimu** [comment]
1.android11
2.抱歉，我不太确定原来的是不是ci版本，但是下载过程中好像没有提示从ci到稳定版
3.app有跳出来更新提示

**Comment by UjuiUjuMandan** [comment]
试试安装CI版本: https://github.com/UjuiUjuMandan/EhViewer/actions 。

原来是在什么地方下载的？

**Comment by yinyingweimu** [comment]
下载了ci版本之后没有闪退了，以前的信息也都还在，哥你是神中神，给你磕了😽以后不敢光存本地收藏了
另外以前更新我都是直接在release下的
