### ISSUE TITLE
最新版彩E不显示画廊可用种子数了

### ISSUE THREAD

**Issue by chikao2024** [UjuiUjuMandan/EhViewer#48]
### 复现步骤 / Step to reproduce

不显示画廊可用(数量)种子数了，只有点击种子后才知道当前画廊是否有种子。

### 预期行为 / Expected behaviour

不用点击种子，即可显示画廊可用种子数

### 实际行为 / Actual Behaviour

应该不用点击即显示种子(数量)

### 应用日志 / App logs

暂无

### 浏览站点 / Browsing site

E-Hentai & Exhentai

### EhViewer 版本号 / EhViewer version code

1.11.1-cc

### EhViewer CI 版本 / EhViewer CI Version

bca115e

### Android 系统版本 / Android version

MIUI 14.0.8

### 设备型号 / Device model

Redme Note 11 Pro

### SoC 型号 / Soc model

MT6877T

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/880#issuecomment-1986026716
