### ISSUE TITLE
默认下载目录在文件管理器内找不到（app内可正常阅读）

### ISSUE THREAD

**Issue by Azzhm** [UjuiUjuMandan/EhViewer#49]
### 复现步骤 / Step to reproduce

https://github.com/UjuiUjuMandan/EhViewer/assets/156394863/8a760fdb-5be4-465a-8f04-f1ec88f5eec6

### 预期行为 / Expected behaviour

在Android/data下应有moe.tarsin.ehviewer文件夹

### 实际行为 / Actual Behaviour

Android/data下并无次文件夹，并且找不到下载的文件在哪

### 应用日志 / App logs

[log-2024-03-22-14-06-24-062.zip](https://github.com/UjuiUjuMandan/EhViewer/files/14718111/log-2024-03-22-14-06-24-062.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.2-cc

### EhViewer CI 版本 / EhViewer CI Version

5c6480a

### Android 系统版本 / Android version

HyperOS1.0.28   Android14

### 设备型号 / Device model

xiaomi14

### SoC 型号 / Soc model

骁龙8 gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
> 不再提供默认下载路径

https://github.com/FooIbar/EhViewer/releases/tag/1.11.0
