### ISSUE TITLE
更新后无法连接exhentai

### ISSUE THREAD

**Issue by Yutsukiowo** [UjuiUjuMandan/EhViewer#53]
### 复现步骤 / Step to reproduce

无

### 预期行为 / Expected behaviour

旧版本正常进入里站

### 实际行为 / Actual Behaviour

更新后我无论重装软件还是退出重新登陆都不能进入里站，显示网络错误
但pc端我是能正常进入里站的，重新登陆也是用pc端上的cookie登陆仍然不行

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.6.9.13

### EhViewer CI 版本 / EhViewer CI Version

26f05a0

### Android 系统版本 / Android version

COloros14

### 设备型号 / Device model

oppo find x6pro

### SoC 型号 / Soc model

忘了

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
你手机开了VPN吗？
