### ISSUE TITLE
点击标签时崩溃

### ISSUE THREAD

**Issue by Kgat9** [UjuiUjuMandan/EhViewer#54]
### 复现步骤 / Step to reproduce

EhViewer    1.11.3.4-cc版本，
1. 只要打开软件浏览作品列表不超过2分钟，软件就会卡顿，崩溃（视频1过大放不上来，看视频2
）
2. 不能点击作品标签搜索，会卡顿崩溃（视频2）

https://github.com/UjuiUjuMandan/EhViewer/assets/149447502/fbc4221e-9037-4e40-8329-7da9eca2aa09

### 预期行为 / Expected behaviour

正常情况应顺畅使用，没有卡顿

### 实际行为 / Actual Behaviour

实际发生卡顿与崩溃

### 应用日志 / App logs

[Uploading com-vpn-free-hotspot-secure-vpnify-160000-49238619-219681331d299c8d472b9d4471e8242d.zip…]()

### 备注 / Addition details

希望能像旧版本一样流畅好用，自打更新了版本后就出现了各种问题o(´^｀)o

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.3.4-cc

### EhViewer CI 版本 / EhViewer CI Version

f5d7d94

### Android 系统版本 / Android version

Android10

### 设备型号 / Device model

OPPO R17

### SoC 型号 / Soc model

PBEM00

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
日志没传上来。

**Comment by Kgat9** [comment]
压缩包内呀？



---原始邮件---
发件人: "ᡠᠵᡠᡳ ᡠᠵᡠ ***@***.***&gt;
发送时间: 2024年4月16日(周二) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UjuiUjuMandan/EhViewer] 1.11.3.4-cc版本新bug。软件崩溃，不能点击标签 (Issue #54)




 
日志没传上来。

**Comment by UjuiUjuMandan** [comment]
@Kgat9 你压缩包根本没传上来。

**Comment by Kgat9** [comment]
我又邮箱回复发给你了，没收到吗？日志文件那个格式上传不了。等下我再发一下压缩包附件吧。也可以给我你的邮箱。还有之后我又得新开个问题😰，返回就卡顿。



---原始邮件---
发件人: "ᡠᠵᡠᡳ ᡠᠵᡠ ***@***.***&gt;
发送时间: 2024年4月18日(周四) 晚上6:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UjuiUjuMandan/EhViewer] 点击标签时崩溃 (Issue #54)




 
@Kgat9 你压缩包根本没传上来。

**Comment by UjuiUjuMandan** [comment]
@Kgat9 请直接到这个页面上传，Email附件我不会收到。

**Comment by Kgat9** [comment]
@UjuiUjuMandan 最新日志文件

[log-2024-04-18-19-34-48-219.zip](https://github.com/UjuiUjuMandan/EhViewer/files/15024268/log-2024-04-18-19-34-48-219.zip)

**Comment by UjuiUjuMandan** [comment]
没有任何崩溃的记录，请尝试复现崩溃之后再上传。

**Comment by Kgat9** [comment]
那是如视频所示非常严重的卡顿，根本无法操作。只能按主页键窗口关闭重打开。

**Comment by UjuiUjuMandan** [comment]
@Kgat9 你刚开的Issue里的日志还是什么都没有，我怀疑你设备的“日志缓冲区大小”被关闭，导致不会记录任何日志，请去开发者设置检查一下。

**Comment by UjuiUjuMandan** [comment]
@Kgat9 我说的是系统设置的“开发者选项”。

https://developer.android.google.cn/studio/debug/dev-options

**Comment by Kgat9** [comment]
> @Kgat9 你刚开的Issue里的日志还是什么都没有，我怀疑你设备的“日志缓冲区大小”被关闭，导致不会记录任何日志，请去开发者设置检查一下。

默认有打开
![日志缓冲区大小](https://github.com/UjuiUjuMandan/EhViewer/assets/149447502/ecad0b7c-a4e1-4ebd-8f4b-3daacbaaab87)

**Comment by UjuiUjuMandan** [comment]
没有日志就无法分析。

我刚才同步了FooIbar的更改，如果你用他的最新CI版本没问题，这边也更新一下。

**Comment by Kgat9** [comment]
他的最新1.11.4版本同样卡顿闪退，我现在只能用绿E和JHT，彩E的快速便捷渐渐久远。


若是需要点开日志文档的话，我这边能点开txt文件。不晓得有无用




内容——“======== packageinfo ========packagename=moe.tarsin.ehviewerversionname=1.11.4versioncode=180055commitsha=71a4e84buildtime=2024/04/21 14:48======== deviceinfo ========board=sdm710bootloader=unknownbrand=oppocpu_abi=arm64-v8acpu_abi2=device=pbem00display=pbem00_11_f.26fingerprint=oppo/pbem00/pbem00:10/qkq1.190918.001/2021060001:user/release-keyshardware=qcomhost=cp-ubuntu-123id=qkq1.190918.001is_debuggable=falseis_emulator=falsemanufacturer=oppomodel=pbem00permissions_review_required=trueproduct=pbem00radio=unknownserial=unknownsupported_32_bit_abis=armeabi-v7a, armeabisupported_64_bit_abis=arm64-v8asupported_abis=arm64-v8a, armeabi-v7a, armeabitags=release-keystime=1667301553000type=userunknown=unknownuser=rootactive_codenames=base_os=codename=relfirst_sdk_int=27incremental=2021060001preview_sdk_fingerprint=relpreview_sdk_int=0release=10resources_sdk_int=29sdk=29sdk_int=29security_patch=2021-05-05memory=7.8 mibmemory_native=20.6 mibmemory_max=384.0 mibmemory_total=7.4 gib”



---原始邮件---
发件人: "ᡠᠵᡠᡳ ᡠᠵᡠ ***@***.***&gt;
发送时间: 2024年5月16日(周四) 晚上6:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UjuiUjuMandan/EhViewer] 点击标签时崩溃 (Issue #54)




 
没有日志就无法分析。
 
我刚才同步了FooIbar的更改，如果你用他的最新CI版本没问题，这边也更新一下。

**Comment by UjuiUjuMandan** [comment]
@Kgat9 

> 打开使用持续集成构建频道更新至最新 CI 版本

请在应用内启用“使用持续集成构建频道更新”并“检查更新”。

**Comment by Kgat9** [comment]
> @Kgat9
> 
> > 打开使用持续集成构建频道更新至最新 CI 版本
> 
> 请在应用内启用“使用持续集成构建频道更新”并“检查更新”。
> 
> 该日志文件中没有任何记录。

最新版开始闪退

https://github.com/UjuiUjuMandan/EhViewer/assets/149447502/4e452177-9274-4bbe-953c-a00673af2f50

**Comment by UjuiUjuMandan** [comment]
>  最新版开始闪退
@Kgat9

这可能是你更新到CI版本之后，又安装了在Release里的旧版，导致数据库降级导致的。

CI版本都在Actions里，请去那里下载最新版。

FooIbar的: https://github.com/FooIbar/EhViewer/actions
我的: https://github.com/UjuiUjuMandan/EhViewer/actions

**Comment by Kgat9** [comment]
> > 最新版开始闪退
> > @Kgat9
> 
> 这可能是你更新到CI版本之后，又安装了在Releases里的旧版，导致数据库降级导致的。
> 
> CI版本都在Actions里，请去那里下载最新版。
> 
> FooIbar的: https://github.com/FooIbar/EhViewer/actions 我的: https://github.com/UjuiUjuMandan/EhViewer/actions

已下载最新1.11.4.3-cc（e53b1be），简单使用暂无明显问题。后续使用再看
