### ISSUE TITLE
配额显示错误

### ISSUE THREAD

**Issue by RMWW** [UjuiUjuMandan/EhViewer#56]
### 复现步骤 / Step to reproduce

我一直是满配额，但最新版彩E更新Cookies登录后只显示5000，即使从彩E的EH>Ehentai设置中通过网页版查看也还是只有5000。 而浏览器和绿E配额均显示正确。

### 预期行为 / Expected behaviour

应该正确显示配额

### 实际行为 / Actual Behaviour

只能显示5000配额

### 应用日志 / App logs

暂无

### 浏览站点 / Browsing site

E-Hentai & Exhentai

### EhViewer 版本号 / EhViewer version code

1.11.3.5-cc

### EhViewer CI 版本 / EhViewer CI Version

ecdf563

### Android 系统版本 / Android version

MIUI 14.0.8 Android 13

### 设备型号 / Device model

Redme Note 11 Pro

### SoC 型号 / Soc model

Dimensity 920

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
“通过网页版查看”和浏览器显示在相同账号下不应该有区别。“满配额”是指50000吗？

**Comment by UjuiUjuMandan** [comment]
你是不是 @chikao2024 ？

**Comment by RMWW** [comment]
> “通过网页版查看”和浏览器显示在相同账号下不应该有区别。“满配额”是指50000吗？我这可以正确显示`0 / 50000`。

可能您测试时没有重新登录，所以配额保持当前值，重新登录后配额就一直只有5000了，而回退旧版就能正常显示。
