### ISSUE TITLE
Feature request: display favorites category name

### ISSUE THREAD

**Issue by soredake** [UjuiUjuMandan/EhViewer#58]
### 需求 / Requirement

Display favorites category name like in [Eros-FE](https://github.com/3003h/Eros-FE):
![image](https://github.com/UjuiUjuMandan/EhViewer/assets/5204968/a52f168a-7fec-4f3a-9054-c6fc49eaf67e)

### 建议实现 / Suggested implements

Display favorites category name.

### 备注 / Addition details

Right now there is no remote names are used, only generic Favorite 1/2/3:
![image](https://github.com/UjuiUjuMandan/EhViewer/assets/5204968/3cfd97d0-2168-44de-b874-fe94ec50b8b5)

### EhViewer 版本号 / EhViewer version code

1.11.4.1-cc

### EhViewer CI 版本 / EhViewer CI Version

1.11.4.1-cc

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by UjuiUjuMandan** [comment]
EhViewer already has this feature since long long ago, and it works well on my machine.

**Comment by UjuiUjuMandan** [comment]
I tried to reproduce this bug. It happens only if you login as first time and have never viewed the Favorite column. 

If you go to Favorite, switch to Cloud Favorites, then as it loads, EhViewer would remember folder names for any longer.

This is not any serious, so report a bug to [FooIbar](https://github.com/FooIbar/EhViewer) if you believe it must be fixed.

**Comment by soredake** [comment]
> I tried to reproduce this bug. It happens only if you login as first time and have never viewed the Favorite column.

I do visit it, and after restarting app remote names are still not loaded.

>This is not any serious, so report a bug to [FooIbar](https://github.com/FooIbar/EhViewer) if you believe it must be fixed.

Will do, thanks.
