### ISSUE TITLE
调整画廊顺序

### ISSUE THREAD

**Issue by aosan1** [UjuiUjuMandan/EhViewer#59]
### 需求 / Requirement

更新前本来可以在下载里按住三条杠手动调整漫画顺序，更新后这个图标没有了，是改到其他位置了还是已经删除这个功能了，如果删除了以后的版本可以再次添加吗😥

### 建议实现 / Suggested implements

请求添加可以调节漫画顺序的图标或者功能

### 备注 / Addition details

无

### EhViewer 版本号 / EhViewer version code

1.11.3.5-cc (ecdf563)

### EhViewer CI 版本 / EhViewer CI Version

26F05A0

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/890#issuecomment-1987033861
