### ISSUE TITLE
缩略图加载不出来

### ISSUE THREAD

**Issue by earth689** [UjuiUjuMandan/EhViewer#6]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.利用cookies登陆eh账号
2.发现缩略图加载不出来，等好久才加载出来一张
![Screenshot_20231024_215054_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/136949376/cdc3bdfc-61d5-4d42-ab8f-2f69f62642fa)

### 预期行为 / Expected behaviour

它应该能像之前的彩e一样快速加载缩略图

### 实际行为 / Actual Behaviour

实际上加载不出来缩略图，部分能加载出来但极
![Screenshot_20231024_215054_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/136949376/d88f4559-203f-48d1-a9da-004b1d805d06)
其慢

### 备注 / Addition details

不知道是不是您的问题，但无论如何都为您能恢复直连功能而表示衷心的感谢

### EhViewer 版本号 / EhViewer version code

1.8.10.1

### EhViewer CI 版本 / EhViewer CI Version

2f85cff

### Android 系统版本 / Android version

HarmonyOS 4.0.0

### 设备型号 / Device model

HUAWEI P60 Pro

### SoC 型号 / Soc model

Snapdragon8+Gen1 4G

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
> 之前的彩e

彩e目前有三个版本：

1. https://github.com/Ehviewer-Overhauled/Ehviewer
2. https://github.com/FooIBar/EhViewer
3. 这个

其中 2 是没有直连功能的，所以你说的可以正常加载应该是指 1 。我建议您去 1 的 Release 下载之前支持域前置的版本安装（您可能需要卸载再安装，因为它的版本号更低）看看表现如何，如果一样很慢就说明不是此分支的问题。

如果您确定是此分支的问题，请在之后去 设置 - 高级 -导出日志 保存日志文件然后传上来，我可能能从中找出原因。

**Comment by Railies** [comment]
我的使用顺序是1->2->3，使用的也是目前最新的版本。1的直连速度确实比较快，缩略图加载是正常的，但目前3直连缩略图加载确实很慢。而且下载方面，不知道是否是因为app影响了clash的转发（对此并不了解），在使用clash的情况下使用3的下载速度远低于1or2（测试是短时间前后分别进行的）

> > 之前的彩e
> 
> 彩e目前有三个版本：
> 
> 1. https://github.com/Ehviewer-Overhauled/Ehviewer
> 2. https://github.com/FooIBar/EhViewer
> 3. 这个
> 
> 其中 2 是没有直连功能的，所以你说的可以正常加载应该是指 1 。我建议您去 1 的 Release 下载之前支持域前置的版本安装（您可能需要卸载再安装，因为它的版本号更低）看看表现如何，如果一样很慢就说明不是此分支的问题。
> 
> 如果您确定是此分支的问题，请在 等待加载出任何缩略图 之后去 设置 - 高级 -导出日志 保存日志文件然后传上来，我可能能从中找出原因。

**Comment by UjuiUjuMandan** [comment]
“等好久才能加载出一张”的表现我只有在一种情况下能复现到：在 设置 - EH 关闭 “强制使用 e-hentai 缩略图服务器” 。

如果你是开的，我目前想不到还慢是什么原因。

不过我建议：如果你是开的，关闭再试试；如果你是关的，开启再试试😅。

还有记得提供日志。

**Comment by earth689** [comment]
感谢您的指导与耐心，确实是因为开了强制试用e站缩略图加载器导致的，现在已恢复正常。

**Comment by UjuiUjuMandan** [comment]
@Railies 你可以去试试刚加回来的域前置，开启之后需要关闭 cronet 集成否则后者优先级更高。

https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6671944289

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer/commit/24a468ea277df635c707c13495b32e814825b975 ，这个选项默认值现在是关闭了。

可能各地网络情况不同，我用 e-hentai 的缩略图服务器会比较快，否则就是一张一张慢慢地加载出来。但是现在有2个人告诉我关了反而比较快...
