### ISSUE TITLE
下载特定画廊的时候下载配额狂飙，但是进度条不变

### ISSUE THREAD

**Issue by RxinnotRstar** [UjuiUjuMandan/EhViewer#62]
### 复现步骤 / Step to reproduce

https://github.com/UjuiUjuMandan/EhViewer/assets/56676566/50880be2-712c-41b2-9da9-290b106bb7e1

### 预期行为 / Expected behaviour

-

### 实际行为 / Actual Behaviour

下载配额以不正常的速度增长

下载进度始终为0

软件里的下载速度和状态栏的下载速度匹配不上

### 应用日志 / App logs

[log-2024-05-22-06-47-03-399.zip](https://github.com/UjuiUjuMandan/EhViewer/files/15396453/log-2024-05-22-06-47-03-399.zip)

### 备注 / Addition details

我勾选了原图下载。

因为我不能确定是程序代码本身的问题还是直连模块的问题，所以我会同时在原分支和直连分支（也就是这里）提同样的issue。

特定的画廊：https://exhentai.org/g/2857166/47fa65cc23

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.5-cc

### EhViewer CI 版本 / EhViewer CI Version

6d6e2f2

### Android 系统版本 / Android version

MIUI 14｜Android 13

### 设备型号 / Device model

redmi note 12 turbo

### SoC 型号 / Soc model

高通骁龙 7+ Gen 2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
我在日志中看到了一些关于文件创建失败的消息，因此猜测是应用没有权限读取下载目录，于是我去系统设置里找到该应用的存储设置，并清除了存储权限，再去下载该画廊并看到了与你的“实际行为”大部分相同的结果，不相同的是配额消耗没你录屏里那么快。

你能试试重新设定下载目录到原目录吗，这会重新授予应用读写该目录的权限。

**Comment by RxinnotRstar** [comment]
> 你能试试重新设定下载途径到原目录吗

感谢您提供的解决方案。

我重新设置了一遍下载路径到，经过测试，在下载路径没有改变的情况下，该画廊的下载功能已经恢复正常。

不过，当时只有特定的画廊才会出现类似这样的下载异常的问题，我在下载其它画廊的时候并没有出现异常。尽管这依然是一个值得探索的问题，但已经不重要了。

希望原分支可以增加文件创建失败时停止下载的功能，避免再次出现无法下载以及配额大量消耗的问题。

**Comment by Loy-K** [comment]
> 你能试试重新设定下载途径到原目录吗，这会重新授予应用读写该目录的权限。

特定画廊：https://e-hentai.org/g/2943254/91e4973586/
我在使用上述方法后问题并没有得到解决，且出现了闪退。
 在换了一个文件夹进行测试时，发现应用重复创建了下载文件夹，且自动创建了其他并未启动下载的文件夹。
![QQ图片20240621120508](https://github.com/UjuiUjuMandan/EhViewer/assets/120195773/d39a015f-7ba5-452e-9be3-86e837faf32b)




### **应用日志 / App logs**
[log-2024-06-21-11-57-29-484.zip](https://github.com/user-attachments/files/15922558/log-2024-06-21-11-57-29-484.zip)

**Comment by Sayaori** [comment]
![image](https://github.com/UjuiUjuMandan/EhViewer/assets/73752368/c69aed8b-7d9c-43df-a820-45d01b28b1f5)

是的我也发现了这个问题

**Comment by UjuiUjuMandan** [comment]
@Loy-K @Sayaori 这两个相似的文件夹名有何区别？

**Comment by Sayaori** [comment]
> @Loy-K @Sayaori 这两个相似的文件夹名有何区别？

很遗憾我已经删掉了这两个文件夹，无法逐个字符对比查看了
并且，再次目前再次下载后只有一个文件夹了，但仍然无法下载且特别消耗配额
另外奇怪的是，他们两个说的特定画廊我是可以正常下载的
也不清楚到底是不是因为标题过长导致的，从我和 @Loy-K 的情况来看可能是的，但 @RxinnotRstar 所指出的特定画廊的标题并不是很长

**Comment by Loy-K** [comment]
> @Loy-K @Sayaori 这两个相似的文件夹名有何区别？

多了个（1），似乎是文件名重复系统自动添加的。
@Sayaori 的特定画廊我这边同样不能下载，但鉴于它在我的收藏夹9里，所以我以前肯定是下载成功过的

今天的多次复现：
①下载清单有画廊时，点击下载后，会创建**1-2**个指定的画廊，并额外创建其他未开启下载的画廊（均下载了第一页），且闪退最迟的一次高达27个，推测不闪退的话会一直创建。
之后每次点击下载会创建**2**个指定的画廊，但不创建额外的未指定画廊。
②清空下载清单后，每次点击下载，会创建**1**个指定的画廊文件夹然后闪退

https://github.com/UjuiUjuMandan/EhViewer/assets/120195773/3d017796-ad82-402c-ba7d-0cd0e6307b63


**对应的日志**：[log-2024-06-22-14-04-03-427.zip](https://github.com/user-attachments/files/15935566/log-2024-06-22-14-04-03-427.zip)



其他的资料，数据清理了没有留日志：

https://github.com/UjuiUjuMandan/EhViewer/assets/120195773/68456b2d-90c4-488c-841d-1090c4477500

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer/issues/1340#issuecomment-2184709111
