### ISSUE TITLE
某些在主页中可以正常看到的画廊在搜索时被隐藏了，在网页端也可以正常显示

### ISSUE THREAD

**Issue by YooZi1999** [UjuiUjuMandan/EhViewer#63]
### 复现步骤 / Step to reproduce

通过在搜索栏中输入或者点击TAG搜索某个关键词，例如tslove或者artist:tslove

### 预期行为 / Expected behaviour

在网页端搜索此关键词，正常显示
![TIM截图20240525111251](https://github.com/UjuiUjuMandan/EhViewer/assets/170781441/be0c6496-8f16-4e71-b02e-1bb85f16a8c3)

### 实际行为 / Actual Behaviour

在APP中搜索同一个关键词，出现什么都没有找到
![TIM图片20240525111420](https://github.com/UjuiUjuMandan/EhViewer/assets/170781441/945a4709-93bd-417a-b217-2879823b6ea5)

### 应用日志 / App logs

[log-2024-05-25-11-15-34-887.zip](https://github.com/UjuiUjuMandan/EhViewer/files/15441395/log-2024-05-25-11-15-34-887.zip)

### 备注 / Addition details

在主页可以正常看到
![TIM图片20240525111425](https://github.com/UjuiUjuMandan/EhViewer/assets/170781441/9c9712c9-1c7a-4a74-abd3-cb9c99804673)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.5-cc

### EhViewer CI 版本 / EhViewer CI Version

6d6e2f2

### Android 系统版本 / Android version

MIUI14.0.5

### 设备型号 / Device model

redmi note 11T PRO

### SoC 型号 / Soc model

天玑8100

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
在应用内搜索的时候别只选 NON-H 。

**Comment by YooZi1999** [comment]
解决了，是我没仔细检查屏蔽列表，打扰了
