### ISSUE TITLE
非bug，也可能算bug，有点功能上的疑问

### ISSUE THREAD

**Issue by guest-zero** [UjuiUjuMandan/EhViewer#67]
### 复现步骤 / Step to reproduce

点击左上工具栏，依次点击设置→下载→恢复下载项或清理下载冗余

### 预期行为 / Expected behaviour

恢复未删除的下载项或清理仍存在的下载项

### 实际行为 / Actual Behaviour

优先清理下载冗余后，显示未发现冗余，但再点击恢复下载项后，仍会恢复下载项，但下载页面没出现多的下载项

### 应用日志 / App logs

无

### 备注 / Addition details

不清楚这个功能是否会清理仍在下载页面，但已经被版权的作品。
且有点题外话，为什么部分在较早期已下载的作品，在不勾选删除图片文件时，再次点击下载会进行重新下载？

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

最新版本

### EhViewer CI 版本 / EhViewer CI Version

最新版本

### Android 系统版本 / Android version

miui 14.0.8

### 设备型号 / Device model

红米note10pro

### SoC 型号 / Soc model

不确定

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by guest-zero** [comment]
以下为补充
![Screenshot_2024-06-05-01-54-24-214_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/2f7a6e25-b9db-4562-ad99-ee95cc14582c)
![Screenshot_2024-06-05-01-54-20-106_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/69764dd1-353b-4c03-845c-a62606fb491e)
![Screenshot_2024-06-05-01-54-15-215_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/4e627cd0-0384-400b-b728-8c3a7d6ea608)
![Screenshot_2024-06-05-01-54-00-044_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/e4936d73-1686-41b6-886a-1bece5c5a6f0)

**Comment by guest-zero** [comment]
以下为补充
![Screenshot_2024-06-05-01-54-00-044_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/6e5a6248-41e8-4d09-9638-75a94a856b37)
![Screenshot_2024-06-05-01-54-15-215_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/d86583ea-ca32-4b0e-ba30-f1b515f5a8df)
![Screenshot_2024-06-05-01-54-20-106_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/64e31d19-3bc9-4c37-82b1-ab3e0e9bf439)
![Screenshot_2024-06-05-01-54-24-214_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/133760269/cf7df874-0bd1-493b-bdf1-97c592b08abf)

**Comment by UjuiUjuMandan** [comment]
我只知道恢复下载项需要请求e站API，其它no idea。去问FooIbar吧。
