### ISSUE TITLE
已被封禁的账号登录时解析失败

### ISSUE THREAD

**Issue by RMWW** [UjuiUjuMandan/EhViewer#68]
### 复现步骤 / Step to reproduce

彩E无法登陆已登月的Cookies，但同样的Cookies绿E却可以正常登陆。

ipb_member_id: 7711946
ipb_pass_hash: 15f08fb3ee7a311293b00d888c6889a7
igneous: cf2fa3bca

### 预期行为 / Expected behaviour

彩E可以正常登陆已登月的Cookies

### 实际行为 / Actual Behaviour

彩E无法登陆已登月的Cookies，但绿E却可以。

https://github.com/UjuiUjuMandan/EhViewer/assets/158696669/d0dbbc66-8736-4d5e-a22f-bf94c3510916

### 应用日志 / App logs

暂无

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC1-cc

### EhViewer CI 版本 / EhViewer CI Version

2ed17da

### Android 系统版本 / Android version

MIUI 11.0.3 Android 9

### 设备型号 / Device model

Redmi Note 8 Pro

### SoC 型号 / Soc model

MediaTek Helio G90T

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by RMWW** [comment]
付录屏

https://github.com/UjuiUjuMandan/EhViewer/assets/158696669/8e7424b6-39b9-4ae4-96d9-5ed622219526

**Comment by UjuiUjuMandan** [comment]
我可以登录。

既然错误是“解析失败”，那就看看发回来的页面是什么吧。在“设置-高级”打开“解析失败时保存页面内容”，然后复现一次解析失败再导出日志传上来吧。

**Comment by chikao2024** [comment]
> 我可以登录。
> 
> 既然错误是“解析失败”，那就看看发回来的页面是什么吧。在“设置-高级”打开“解析失败时保存页面内容”，然后复现一次解析失败再导出日志传上来吧。

彩E提示Cookies错误无法登陆，绿E却是可以的，目前仅限于已登月的9位igneous的Cookies。

**Comment by RMWW** [comment]
> 我可以登录。
> 
> 既然错误是“解析失败”，那就看看发回来的页面是什么吧。在“设置-高级”打开“解析失败时保存页面内容”，然后复现一次解析失败再导出日志传上来吧。

关键是无法登陆啊，这就无法导出日志了吧。还有您是用所提供的已登月的Cookies登陆进彩E的吗？

**Comment by UjuiUjuMandan** [comment]
> 关键是无法登陆啊，这就无法导出日志了吧。

复现一次然后游客模式进去导出。

> 还有您是用所提供的已登月的Cookies登陆进彩E的吗？

是的。

**Comment by UjuiUjuMandan** [comment]
人呢？

**Comment by RMWW** [comment]
> 人呢？
 55555发错了😓，刚发了正常使用的Cookies，希望别出事😭，我重新编辑又发了登月的Cookies，您再试下，这两个录屏里的Cookies是不一样的。

**Comment by UjuiUjuMandan** [comment]
@RMWW 这个账号的密码你知道吗？

**Comment by RMWW** [comment]
> @RMWW 这个账号的密码你知道吗？我要向上游反馈，但是他们没有 Cookie 登陆。

这个账号和密码没有，只有Cookies。

**Comment by UjuiUjuMandan** [comment]
没关系，我请求Tenboro了另一个登月账号用于测试。

**Comment by RMWW** [comment]
> 没关系，我请求Tenboro了另一个登月账号用于测试。

这个厉害了直接找菠萝了哈
