### ISSUE TITLE
下载种子失败

### ISSUE THREAD

**Issue by RMWW** [UjuiUjuMandan/EhViewer#69]
### 复现步骤 / Step to reproduce

彩E无法下载种子，一直提示下载种子文件失败，而绿E和白E均能正常下载。

https://github.com/UjuiUjuMandan/EhViewer/assets/158696669/b23a93e9-8448-4ffa-960e-f3a58c36b8de

### 预期行为 / Expected behaviour

可以正常下载种子文件

### 实际行为 / Actual Behaviour

无法下载种子文件

### 应用日志 / App logs

暂无

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2-cc

### EhViewer CI 版本 / EhViewer CI Version

b1b8b42

### Android 系统版本 / Android version

MIUI 11.0.3 Android 9

### 设备型号 / Device model

Redmi Note 8 Pro

### SoC 型号 / Soc model

MediaTek Helio G90T

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
无法复现，需要日志。

**Comment by UjuiUjuMandan** [comment]
另外请说维护者名字，别用颜色区分，现在每个颜色各有3个版本。

**Comment by RMWW** [comment]
> 无法复现，需要日志和画廊链接。

画廊链接和日志: https://exhentai.org/g/2944453/369c593f07
[log-2024-06-08-14-35-03-251.zip](https://github.com/user-attachments/files/15747051/log-2024-06-08-14-35-03-251.zip)

**Comment by RMWW** [comment]
> 另外请说维护者名字，别用颜色区分，现在每个颜色各有3个版本。小白的我记得不能直连吧。

白E是AdNotFound的分支，可以直连的。

**Comment by UjuiUjuMandan** [comment]
三周前的一次合并没注意，误删了审查规避的代码。
