### ISSUE TITLE
全新安装不显示标签翻译

### ISSUE THREAD

**Issue by 1183807453** [UjuiUjuMandan/EhViewer#7]
### 复现步骤 / Step to reproduce

0.全新安装应用
1.登录账户
2.勾选显示标签翻译

### 预期行为 / Expected behaviour

标签翻译显示为中文

### 实际行为 / Actual Behaviour

不显示标签翻译
![Screenshot_2023-10-26-14-56-04-128_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/142478672/d2feefbd-cfe1-4a5a-a1db-34ef3d0fea14)
![Screenshot_2023-10-26-14-55-53-229_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/142478672/f359aec8-9c9b-4987-9f19-736552fe34fe)

### 应用日志 / App logs

[log-2023-10-26-14-58-52-539.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13173951/log-2023-10-26-14-58-52-539.zip)

### EhViewer 版本号 / EhViewer version code

1.8.10.1

### EhViewer CI 版本 / EhViewer CI Version

897d9a2

### Android 系统版本 / Android version

MIUI14

### 设备型号 / Device model

Redmi K50

### SoC 型号 / Soc model

天玑8100

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 1183807453** [comment]
因为没有VPN，所以不确定是上游的问题还是分支的问题

**Comment by UjuiUjuMandan** [comment]
下载翻译数据的 [URL](https://github.com/UjuiUjuMandan/EhViewer/blob/1.8.x.x/app/src/main/res/values/arrays.xml#L202) 的域名已更换为 jsDelivr ，根据 [ITDOG](https://www.itdog.cn/http/) 的测试结果，其连通性比 `raw.githubusercontent.com` 要好。

你可以去 https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6655171870 下载最新的构建来测试。

**Comment by 1183807453** [comment]
已经解决了，谢谢！
