### ISSUE TITLE
进入画廊中加载图片或者原图是（大概）会弹出重新加载连续多次

### ISSUE THREAD

**Issue by emmpp** [UjuiUjuMandan/EhViewer#70]
### 复现步骤 / Step to reproduce

不是每次出现不清楚如何具体情况是什么

### 预期行为 / Expected behaviour

无

### 实际行为 / Actual Behaviour

无

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

eh

### EhViewer 版本号 / EhViewer version code

1.11.6

### EhViewer CI 版本 / EhViewer CI Version

311293a

### Android 系统版本 / Android version

13

### 设备型号 / Device model

iqoo

### SoC 型号 / Soc model

2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
![image](https://github.com/UjuiUjuMandan/EhViewer/assets/125150101/eebcf632-a703-45c6-9bb8-202cfdc64623)

**Comment by UjuiUjuMandan** [comment]
看不懂你讲的中文，修不了。

**Comment by emmpp** [comment]
就是点进画廊阅读时会闪退至阅读的画廊主页，出现在未下载的画廊，并且会出现连续闪退😂

**Comment by UjuiUjuMandan** [comment]
确认在阅读页面NPE了，等他修。
