### ISSUE TITLE
新版本浏览从上到下（连续）和条漫会崩溃

### ISSUE THREAD

**Issue by MidK284** [UjuiUjuMandan/EhViewer#71]
### 复现步骤 / Step to reproduce

打开已下载漫画，翻了十页左右自动崩溃到下载界面

### 预期行为 / Expected behaviour

能正常浏览

### 实际行为 / Actual Behaviour

大概翻了十页左右就会崩溃

### 应用日志 / App logs

[log-2024-06-09-02-35-56-796.zip](https://github.com/user-attachments/files/15749301/log-2024-06-09-02-35-56-796.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.6.RC2-cc

### EhViewer CI 版本 / EhViewer CI Version

311293a

### Android 系统版本 / Android version

realme ui4.0，Android13

### 设备型号 / Device model

realmeGT Neo2

### SoC 型号 / Soc model

天玑1200

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
FooIbar#1290

**Comment by 1183807453** [comment]
foolbar修复了这个bug，什么时候可以合并更新？
