### ISSUE TITLE
无法在搜索栏打字，无法使用键盘输入和搜索。

### ISSUE THREAD

**Issue by EDMI88** [UjuiUjuMandan/EhViewer#72]
### 复现步骤 / Step to reproduce

因为搜索也是靠键盘回车，所以即使粘贴了文字进入搜索栏一样无法搜索。

### 预期行为 / Expected behaviour

他应该可以输入并且使用键盘搜索按钮的

### 实际行为 / Actual Behaviour

实际上并不可以

### 应用日志 / App logs

无

### 备注 / Addition details

如果可以，希望增加一个类似图片搜索的左下角应用内启动的搜索按钮，这样至少可以靠复制粘贴后使用应用内的按钮进行搜索

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC1

### EhViewer CI 版本 / EhViewer CI Version

1.11.6-RC1

### Android 系统版本 / Android version

HarmonyOS 3.0.0.208

### 设备型号 / Device model

荣耀330Pro

### SoC 型号 / Soc model

麒麟990

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
这不是和 #52 完全相同么？

**Comment by EDMI88** [comment]
> 这不是和 #52 完全相同么？

那我算是补充了一下我是鸿蒙系统加提个建议吧

**Comment by UjuiUjuMandan** [comment]
当然是鸿蒙，#52 和FooIbar那里的报告都说是鸿蒙。
