### ISSUE TITLE
阅读时快速滑动导致闪退

### ISSUE THREAD

**Issue by cclyfblink** [UjuiUjuMandan/EhViewer#73]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.点开一个漫画，阅读
2.快速向上滑动

### 预期行为 / Expected behaviour

不crash

### 实际行为 / Actual Behaviour

前几次会闪退到漫画详情页面，多次闪退后就直接退到桌面

### 应用日志 / App logs

TIME=2024-06-14-01-15-16-229

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.11.6-RC1-cc
VersionCode=180056
CommitSha=293312b
CommitTime=2024-06-07 02:37

======== DeviceInfo ========
BOARD=lahaina
BOOTLOADER=G9910ZHS8GXE2
BRAND=samsung
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=o1q
DISPLAY=UP1A.231005.007.G9910ZHS8GXE2
FINGERPRINT=samsung/o1qzhx/o1q:14/UP1A.231005.007/G9910ZHS8GXE2:user/release-keys
HARDWARE=qcom
HOST=21DKG909
ID=UP1A.231005.007
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=samsung
MODEL=SM-G9910
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=o1qzhx
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=QTI
SOC_MODEL=SM8350
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=release-keys
TIME=1716184064000
TYPE=user
UNKNOWN=unknown
USER=dpi
ACTIVE_CODENAMES=
BASE_OS=samsung/o1qzhx/o1q:14/UP1A.231005.007/G9910ZHU7GXDE:user/release-keys
CODENAME=REL
INCREMENTAL=G9910ZHS8GXE2
KNOWN_CODENAMES={HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
MEDIA_PERFORMANCE_CLASS=0
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=14
RELEASE_OR_CODENAME=14
RELEASE_OR_PREVIEW_DISPLAY=14
SDK=34
SDK_INT=34
SECURITY_PATCH=2024-05-01
SEM_FIRST_SDK_INT=30
SEM_INT=3401
SEM_PLATFORM_INT=150100
MEMORY=20.1 MiB
MEMORY_NATIVE=44.1 MiB
MEMORY_MAX=256.0 MiB
MEMORY_TOTAL=7.2 GiB

======== CrashInfo ========
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at Rj0.a(Unknown Source:116)
	at Qj0.handleMessage(Unknown Source:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC1-cc

### EhViewer CI 版本 / EhViewer CI Version

293312b

### Android 系统版本 / Android version

14

### 设备型号 / Device model

Samsung S21

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
#1290
下个版本会修复。
