### ISSUE TITLE
条漫模式闪退

### ISSUE THREAD

**Issue by Sayaori** [UjuiUjuMandan/EhViewer#76]
### 复现步骤 / Step to reproduce

使用条漫模式看韩漫闪退

https://github.com/UjuiUjuMandan/EhViewer/assets/73752368/15e1bf2f-3f98-4c06-8d8e-7f856d2b55dc

### 预期行为 / Expected behaviour

不闪退

### 实际行为 / Actual Behaviour

闪退了

### 应用日志 / App logs

[log-2024-07-02-00-34-57-225.zip](https://github.com/user-attachments/files/16056613/log-2024-07-02-00-34-57-225.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2

### EhViewer CI 版本 / EhViewer CI Version

b1b8b42

### Android 系统版本 / Android version

安卓13/ColorOS13

### 设备型号 / Device model

一加9pro

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
#70
