### ISSUE TITLE
图片分辨率后续加载变低

### ISSUE THREAD

**Issue by 947zyz** [UjuiUjuMandan/EhViewer#8]
### 复现步骤 / Step to reproduce

![-73abad9572899190](https://github.com/UjuiUjuMandan/EhViewer/assets/149185072/54f54984-c47f-4fee-aef6-9b544ebbb491)
https://forums.e-hentai.org/index.php?showtopic=244935
由于此则公告，图片默认分辨率变低的问题，该问题已向[上游](https://github.com/FooIbar/EhViewer/issues/111) 反馈过，得到解决方法通过修改EH网站上的设置改变自动分辨率为1280x，已得到解决，测试正常。
![Screenshot_2023-10-28-10-09-49-564_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/149185072/96a57b88-3b39-4e2a-904a-eba57d35b2fd)
但使用1.8.10.2-censorcircum该版本时发生了类似问题，在EH网站设置中选择默认图片分辨率为1280x的情况下，选择画廊中的随机一张图片（该画廊不曾有图片缓存），选择的那张图片加载分辨率正常为1280x，但后续预载的图片仍为低分辨率，希望查明原因。

### 预期行为 / Expected behaviour

所有的图片分辨率应都为1280x

### 实际行为 / Actual Behaviour

只有第一张选中的图片加载分辨率为1280x，后续加载的图片分辨率都为低分辨率

### 应用日志 / App logs

[log-2023-10-28-10-38-05-367.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13194271/log-2023-10-28-10-38-05-367.zip)

### EhViewer 版本号 / EhViewer version code

1.8.10.2-censorcircum

### EhViewer CI 版本 / EhViewer CI Version

03f3b9c

### Android 系统版本 / Android version

MIUI 14.0.19 (Android 13)

### 设备型号 / Device model

Redmi Note 12 Turbo

### SoC 型号 / Soc model

骁龙 7+ Gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
日志中可以看到有一次 1280 的请求，后续都是 780 。我不清楚为什么会这样。我用自己的账号测试了也未能复现。

我建议你重新登录试试？

**Comment by 947zyz** [comment]
重新登录和卸载重装后都还是这种情况，但使用上游提供的版本就没有问题，很奇怪。

**Comment by 947zyz** [comment]
重新登录和卸载重装后都还是这种情况，但使用上游提供的版本就没有问题，很奇怪。

**Comment by 947zyz** [comment]
重新登录和卸载重装后都还是这种情况，但使用上游提供的版本就没有问题，很奇怪。

**Comment by UjuiUjuMandan** [comment]
我猜测你只修改了 https://exhentai.org/uconfig.php 的分辨率而没有修改 https://e-hentai.org/uconfig.php 的？

**Comment by 947zyz** [comment]
> 我猜测你只修改了https://exhentai.org/uconfig.php的分辨率而没有修改https://e-hentai.org/uconfig.php的？

解决了，果然是这个问题，感谢提供帮助
