### ISSUE TITLE
部分画廊无法获取到 ComicInfo.xml 或者ComicInfo.xml为空

### ISSUE THREAD

**Issue by Kuma15781** [UjuiUjuMandan/EhViewer#80]
### 复现步骤 / Step to reproduce

1.重新安装应用
2.下载[GID：1369315](https://e-hentai.org/g/1369315/fdf2924b4f/) 
https://e-hentai.org/g/1369315/fdf2924b4f/
3.下载目录中未出现ComicInfo.xml

### 预期行为 / Expected behaviour

应该出现 ComicInfo.xml 文件

### 实际行为 / Actual Behaviour

未出现 ComicInfo.xml 文件

### 应用日志 / App logs

[logs + 下载目录 ComicInfo.xml.zip](https://github.com/user-attachments/files/16570586/logs.%2B.ComicInfo.xml.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.7

### EhViewer CI 版本 / EhViewer CI Version

f4fff83

### Android 系统版本 / Android version

OriginOS 3 (安卓13）

### 设备型号 / Device model

IQOO Z8X

### SoC 型号 / Soc model

6 gen 1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
下载任务完成才会生成 ComicInfo.xml 吧？

**Comment by UjuiUjuMandan** [comment]
合并了，最新的 CI 构建应该没有这个问题了。
