### ISSUE TITLE
突然出现缩略图看不了外面正常，点入画廊中不行

### ISSUE THREAD

**Issue by emmpp** [UjuiUjuMandan/EhViewer#81]
### 复现步骤 / Step to reproduce

![Screenshot_20240816_224622](https://github.com/user-attachments/assets/ea05cb7f-8bcf-4f08-923e-b82df107ef41)
![Screenshot_20240816_224017](https://github.com/user-attachments/assets/769c40e9-a49c-4fe0-991a-86a85e5aea5f)

### 预期行为 / Expected behaviour

，

### 实际行为 / Actual Behaviour

，

### 应用日志 / App logs

，

### 备注 / Addition details

，，

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

1.11.7.2

### EhViewer CI 版本 / EhViewer CI Version

479d924

### Android 系统版本 / Android version

13

### 设备型号 / Device model

，

### SoC 型号 / Soc model

888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Kuma15781** [comment]
我这 1.11.7-cc 版本是正常的

**Comment by emmpp** [comment]
> 我这1.11.7-cc版本是正常的

那我也不清楚如何复现刚刚我进来我问题上面也有一个一样情况的

**Comment by Kuma15781** [comment]
> > 我这1.11.7-cc版本是正常的
> 
> 那我也不清楚如何复现刚刚我进来我问题上面也有一个一样情况的

你切换一下表站测试下
还有你是哪家运营商的？

**Comment by emmpp** [comment]
> > > 我这1.11.7-cc版本是正常的
> > 
> > 
> > 那我也不清楚如何复现刚刚我进来我问题上面也有一个一样情况的
> 
> 你切换一下表站测试下 还有你是哪家运营商的？

表站正常，卡是移动和联动都不行

**Comment by YuuzhanLiu** [comment]
缩略图服务器换了，上游的版本还没更新
等新版本改了就行

**Comment by UjuiUjuMandan** [comment]
已经合并上游修复。

**Comment by hbxxgl** [comment]
表站怎么也突然加载不了缩略图了

**Comment by hbxxgl** [comment]
> 已经合并上游修复。

为什么昨天开始表站缩略图也加载不出来了

**Comment by UjuiUjuMandan** [comment]
@hbxxgl 你的表站设置的缩略图是普通还是大图？

https://e-hentai.org/uconfig.php

**Comment by hbxxgl** [comment]
> @hbxxgl 你的表站设置的缩略图是普通还是大图？
> 
> https://e-hentai.org/uconfig.php

普通

**Comment by UjuiUjuMandan** [comment]
@hbxxgl  https://github.com/UjuiUjuMandan/EhViewer/issues/83#issuecomment-2294681316
