### ISSUE TITLE
缩略图全部无法加载

### ISSUE THREAD

**Issue by Cathjoe** [UjuiUjuMandan/EhViewer#82]
### 复现步骤 / Step to reproduce

1

### 预期行为 / Expected behaviour

正常加载缩略图

### 实际行为 / Actual Behaviour

全部无法加载缩略图
![Screenshot_2024-08-17-02-32-25-877_moe tarsin ehviewer](https://github.com/user-attachments/assets/1c021a8e-3092-4cff-8fe0-28b36db33d02)

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

全部

### EhViewer 版本号 / EhViewer version code

1.11.72

### EhViewer CI 版本 / EhViewer CI Version

1

### Android 系统版本 / Android version

1

### 设备型号 / Device model

1

### SoC 型号 / Soc model

1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
#81
