### ISSUE TITLE
1.11.7.2-cc版本的ehviewer里，进入画廊后翻页无论是本地缓存的还是在线看的，都有一个一闪而过的加载转圈，观看体验和闪光弹一样

### ISSUE THREAD

**Issue by alorplte** [UjuiUjuMandan/EhViewer#83]
### 复现步骤 / Step to reproduce

1.11.7.2-cc版本的ehviewer里，进入画廊后翻页无论是本地缓存的还是在线看的，都有一个一闪而过的加载转圈，观看体验和闪光弹一样

### 预期行为 / Expected behaviour

1.11.7.2-cc版本的ehviewer里，进入画廊后翻页无论是本地缓存的还是在线看的，都有一个一闪而过的加载转圈，观看体验和闪光弹一样

### 实际行为 / Actual Behaviour

1.11.7.2-cc版本的ehviewer里，进入画廊后翻页无论是本地缓存的还是在线看的，都有一个一闪而过的加载转圈，观看体验和闪光弹一样

### 应用日志 / App logs

1.11.7.2-cc版本的ehviewer里，进入画廊后翻页无论是本地缓存的还是在线看的，都有一个一闪而过的加载转圈，观看体验和闪光弹一样

### 备注 / Addition details

我是从1.11.6-rc2-cc更新到1.11.7.2-cc的，之前版本没有这情况

### 浏览站点 / Browsing site

都有

### EhViewer 版本号 / EhViewer version code

1.11.7.2-cc

### EhViewer CI 版本 / EhViewer CI Version

不知道

### Android 系统版本 / Android version

miui14.0.3

### 设备型号 / Device model

xiaomi 13

### SoC 型号 / Soc model

二代晓龙8

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
录屏？

**Comment by alorplte** [comment]
https://gofile.io/d/9HF7Yq
关闭翻页动画就会有这种情况，不关闭翻页动画对于变体集的作品观感奇怪，而且翻页动画对于有延迟的感觉

**Comment by UjuiUjuMandan** [comment]
无法复现。

https://github.com/user-attachments/assets/2e4427cb-5e19-4532-9074-8d712e32847e

**Comment by alorplte** [comment]
不是滑动，就是点击翻页，滑动翻页我也正常

**Comment by alorplte** [comment]
大佬能不能给个降版本装1.11.6-rc2-cc的包

**Comment by alorplte** [comment]
我这可能还有本地缓存太多的原因，本地下载有11400多本，300多g空间

**Comment by UjuiUjuMandan** [comment]
下载这个版本 https://github.com/UjuiUjuMandan/EhViewer/actions/runs/10429800048 

或者设置里开 CI 频道更新试试。

**Comment by alorplte** [comment]
谢谢大佬，现在正常了
