### ISSUE TITLE
搜索功能问题

### ISSUE THREAD

**Issue by Ferraridino001** [UjuiUjuMandan/EhViewer#84]
### 复现步骤 / Step to reproduce

0重新安装应用
1登入账号选择exhentai，搜索失败
2更换为ehentai，部分搜索成功

### 预期行为 / Expected behaviour

可以在exhentai界面搜索到ehentai全部内容

### 实际行为 / Actual Behaviour

无法在exhentai搜索到ehentai内容
![Screenshot_20240818_165555](https://github.com/user-attachments/assets/89cd6ae1-5473-494f-89d9-4085301f13c1)
![Screenshot_20240818_165545](https://github.com/user-attachments/assets/47a6aab0-e2b6-47b4-8056-9f5edb772abe)

### 应用日志 / App logs

[log-2024-08-18-16-57-30-037.zip](https://github.com/user-attachments/files/16647752/log-2024-08-18-16-57-30-037.zip)

### 浏览站点 / Browsing site

E-Hentai, ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.7.2

### EhViewer CI 版本 / EhViewer CI Version

479d924

### Android 系统版本 / Android version

OriginOS3

### 设备型号 / Device model

Iqoo neo8

### SoC 型号 / Soc model

骁龙8+gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
去网页试试是否 可以在exhentai界面搜索到ehentai全部内容 。

**Comment by Ferraridino001** [comment]
> 去网页试试是否 可以在exhentai界面搜索到ehentai全部内容 。
> 
> * https://e-hentai.org
> * https://exhentai.org

![Screenshot_20240818_173543](https://github.com/user-attachments/assets/e1553b97-6083-4ea1-ba71-fe45eeba0698)
网页可以的

**Comment by UjuiUjuMandan** [comment]
请使用相同的关键词，分别提供1、2、3、4的截图。

platform|e-hentai|exhentai
---|----|---
应用|1|2
网页|3|4

**Comment by Ferraridino001** [comment]
> > 去网页试试是否 可以在exhentai界面搜索到ehentai全部内容 。
> > 
> > * https://e-hentai.org
> > * https://exhentai.org
> 
> ![Screenshot_20240818_173543](https://private-user-images.githubusercontent.com/52492457/358896861-e1553b97-6083-4ea1-ba71-fe45eeba0698.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzQ5MzYsIm5iZiI6MTcyMzk3NDYzNiwicGF0aCI6Ii81MjQ5MjQ1Ny8zNTg4OTY4NjEtZTE1NTNiOTctNjA4My00ZWExLWJhNzEtZmU0NWVlYmEwNjk4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA5NTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNTNmODUwYzNjMDdhZTY4NjliMjU0MDZjNTlkYmMyZmRlMzIyMDNjNGY2N2MwNjlmMTYwNjkxODcxOWI4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RAvGFvE407LkxyPmT46N8Uwf0MWPDACYTvTLK236XfQ) 网页可以的

您好，我再次重装了两个变体，现在问题已经解决了，可以搜到了
