### ISSUE TITLE
闪退bug

### ISSUE THREAD

**Issue by Ferraridino001** [UjuiUjuMandan/EhViewer#86]
### 复现步骤 / Step to reproduce

1重新安装应用
2登陆后发现sad panda,账号有eh权限，但是无法访问eh
3应用中eh设置选项卡无法打开，打开后马上闪退

https://github.com/user-attachments/assets/6930f0cb-0727-416a-887c-28c70673a46e

### 预期行为 / Expected behaviour

正常登录后正常显示ex站内容

### 实际行为 / Actual Behaviour

打开ex站后闪退，sad panda

### 应用日志 / App logs

[log-2024-08-26-23-27-42-020.zip](https://github.com/user-attachments/files/16750588/log-2024-08-26-23-27-42-020.zip)

### 浏览站点 / Browsing site

E-hentai, Ex-hentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

5bb0333

### Android 系统版本 / Android version

Origin OS3

### 设备型号 / Device model

iqoo neo8

### SoC 型号 / Soc model

骁龙8+gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Ferraridino001** [comment]
再次更换账号后（有ex权限）后没有闪退，但是还是选择里区后显示sad panda
![Uploading Screenshot_20240826_234835.jpg…]()

**Comment by Ferraridino001** [comment]
登录自建账号（暂时没有里区权限）访问eh设置界面也会闪退

**Comment by Ferraridino001** [comment]
更换为之前的自建号（使用美国节点登录网页版）后解锁了里区权限，但是点击应用的eh界面设置函数闪退

**Comment by Steve-337** [comment]
e站更改了配额系统，上游已修复等待同步
https://github.com/FooIbar/EhViewer/issues/1563
