### ISSUE TITLE
WSA用户更新到最新版本后无法键盘输入左右键翻页

### ISSUE THREAD

**Issue by pujx233** [UjuiUjuMandan/EhViewer#89]
### 复现步骤 / Step to reproduce

配置WSA按装最新版本APP

### 预期行为 / Expected behaviour

可以键盘输入↔️翻页

### 实际行为 / Actual Behaviour

无法通过键盘翻页，目前只能通过鼠标拖动翻页

### 应用日志 / App logs

这个应该没有日志信息...

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-cc

### EhViewer CI 版本 / EhViewer CI Version

5bb0333

### Android 系统版本 / Android version

WSA

### 设备型号 / Device model

Thinkbook14+ 2022

### SoC 型号 / Soc model

6800H

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
https://github.com/FooIbar/EhViewer

**Comment by UjuiUjuMandan** [comment]
我不用WSA，无法帮你复现，自己下载 https://github.com/FooIbar/EhViewer 再报告给他们吧。

**Comment by UjuiUjuMandan** [comment]
另外桌面设备可以试试全平台的 JHenTai ，我就在用:

- https://github.com/jiangtian616/JHenTai

或者直接用网页。
