### ISSUE TITLE
无法直连里站

### ISSUE THREAD

**Issue by chensite6** [UjuiUjuMandan/EhViewer#9]
### 复现步骤 / Step to reproduce

您好，我在今天下载了您的app，一开始还可以直连，后来因为图片分辨率很低，我重装了app，之后就无法直连里站了
![Screenshot_2023-10-28-14-38-02-451_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/149228388/4ed0e0df-983f-43a9-8476-040ece1c3f74)

### 预期行为 / Expected behaviour

直连里站

### 实际行为 / Actual Behaviour

![Screenshot_2023-10-28-14-38-02-451_moe tarsin ehviewer](https://github.com/UjuiUjuMandan/EhViewer/assets/149228388/543ba349-41b6-4e6e-98a5-1d608858df72)

### 应用日志 / App logs

[log-2023-10-28-14-56-22-934.zip](https://github.com/UjuiUjuMandan/EhViewer/files/13194739/log-2023-10-28-14-56-22-934.zip)

### EhViewer 版本号 / EhViewer version code

1.8.10.2-censorcircum

### EhViewer CI 版本 / EhViewer CI Version

03f3b9c

### Android 系统版本 / Android version

MIUI13.0.13

### 设备型号 / Device model

红米k40pro+

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
Duplicate of #1 .

**Comment by UjuiUjuMandan** [comment]
我没想到 QUIC 在这么多地区表现差劲。别用了，去 https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6671944289 下载加回域前置的版本，打开域前置关闭 cronet 。

**Comment by 1183807453** [comment]
下载了SNI版本，感觉下载速度不如QUIC，要不出一个二选一的版本，让用户根据实际选项选择是QUIC直连还是SNI直连？或者网络出错的时候自动跳转直连方式？

**Comment by UjuiUjuMandan** [comment]
> 要不出一个二选一的版本，让用户根据实际选项选择是QUIC直连还是SNI直连

我就是这样想的，最新 CI 版本里就是 域前置 和 Cronet 集成 二选一。

> 或者网络出错的时候自动跳转直连方式？

没有这个打算。
