### ISSUE TITLE
华为平板M3青春版 无法下载图片；下载速度为0，但是配额在消耗

### ISSUE THREAD

**Issue by RxinnotRstar** [UjuiUjuMandan/EhViewer#90]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/b11c4e25-357d-4289-a7af-e6f6bf17d685

### 预期行为 / Expected behaviour

-

### 实际行为 / Actual Behaviour

下载速度为0，下载进度为0，但是配额消耗了。

### 应用日志 / App logs

[log-2024-09-15-03-10-55-580.zip](https://github.com/user-attachments/files/17003700/log-2024-09-15-03-10-55-580.zip)

### 备注 / Addition details

这个问题在 [SXJ版的Ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ) 也出现了。

这是我用“设备信息 by 流舟”导出的设备信息：
[redacted]

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

be83105

### Android 系统版本 / Android version

EMUI 5.1.3；Android 7.0

### 设备型号 / Device model

华为平板M3-青春版（CPN-AL00）

### SoC 型号 / Soc model

高通骁龙 435

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer/issues/62#issuecomment-2123827409

**Comment by UjuiUjuMandan** [comment]
怎么是同一个人？

**Comment by RxinnotRstar** [comment]
> 怎么是同一个人？

当时是特定画廊，现在是这个设备的所有画廊

**Comment by zyl3638** [comment]
我不知道



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月16日(周一) 下午2:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [UjuiUjuMandan/EhViewer] 华为平板M3青春版 无法下载图片；下载速度为0，但是配额在消耗 (Issue #90)




  
怎么是同一个人？
  
当时是特定画廊，现在是这个设备的所有画廊

**Comment by UjuiUjuMandan** [comment]
@RxinnotRstar 
我在日志中看到大量的 net::ERR_CERT_AUTHORITY_INVALID ，推测是这个 Android 版本的的根证书库没更新 hath.network 用的 Let's Encrypt CA。见此: https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686 。

**Comment by RxinnotRstar** [comment]
> 这个设备，你用浏览器打开 https://e-hentai.org/g/1708650/efa651bd38/ 看看能看到大图吗？

测试浏览器：X浏览器（基于webview）
翻墙之后，我可以正常在浏览器阅读大图。
图片链接是“`.hath.network`”的。

但是翻墙之后打开EhViewer，会提示：

```
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

此时 设置-EH 的图片配额可正常获取_（我是捐赠用户，不受影响）_。

**Comment by UjuiUjuMandan** [comment]
> X 浏览器

该浏览器根本不验证 TLS 证书。

https://badssl.com/dashboard/ 显示过期、自签和域名不匹配依然可以连接。

**Comment by RxinnotRstar** [comment]
> 该浏览器根本不验证 TLS 证书。

好的，那我换一个。
测试浏览器：`iceraven` 浏览器（基于firefox）

使用 badssl 测试过了，该浏览器会校验证书。

翻墙之后，可以正常使用`hath.network`提供的服务。

没有开启“http模式”，也就是此时使用`h@h`加载。

EhViewer依然无法显示图像。

![IMG_20240917_131615.jpg](https://github.com/user-attachments/assets/b705385b-bb1c-4386-989f-baa9ff616423)

**Comment by UjuiUjuMandan** [comment]
Firefox 系都有自己的根证书库，不看系统的。

**Comment by RxinnotRstar** [comment]
https://github.com/dev-macgyver/PhotoEditor

逮到一个。

这个没有。

**Comment by UjuiUjuMandan** [comment]
这玩意都没开源。怎么，它能打开 hath.network 图吗？

为什么没办法打开，我在地址栏输入 https://badssl.com/dashboard/ 就行了。

**Comment by RxinnotRstar** [comment]
> 这玩意都没开源。怎么，它能打开 hath.network 图吗？
> 
> 为什么没办法打开，我在地址栏输入 https://badssl.com/dashboard/ 就行了。

照片编辑器的内置浏览器：
- 打不开hath.network。
- 打不开badssl，我猜是因为这网站用的证书系统不支持，和上一条一样。
- 打得开[360搜索](https://www.so.com)。

**Comment by UjuiUjuMandan** [comment]
> 打不开hath.network。
> 打不开badssl，我猜是因为这网站用的证书系统不支持，和上一条一样。

是预期行为，两者的 CA 都是 ISRG Root X1 。

**Comment by UjuiUjuMandan** [comment]
你可以试试这个教程来手动信任此 CA: 

- https://community.auth0.com/t/how-to-install-the-isrg-root-x1-certificate-on-android/130286

**Comment by RxinnotRstar** [comment]
> 你可以试试这个教程

感谢您提供的教程。

虽然这份教程并没有解决我的问题（也许是我操作有错误？），所以我打算通过使用捐赠者特有的http模式来缓解这个问题了。

**Comment by UjuiUjuMandan** [comment]
> 这份教程并没有解决我的问题

安装证书时应该有2个用途选项：

- Wi-Fi
- VPN和应用

如果除此之外还有第三个选项，CA，就选择这个试试。

**Comment by UjuiUjuMandan** [comment]
> 这份教程并没有解决我的问题

https://github.com/UjuiUjuMandan/EhViewer/actions/runs/10906382882

这个版本应该会尊重自定义证书了。

**Comment by RxinnotRstar** [comment]
> 如果除此之外还有第三个选项，CA，就选择这个试试。

这个倒是没有。

**Comment by RxinnotRstar** [comment]
> https://github.com/UjuiUjuMandan/EhViewer/actions/runs/10906382882
> 
> 这个版本应该会尊重自定义证书了。
> 
> 

已确认：该版本配合自定义证书，已修复这个问题。

**Comment by RxinnotRstar** [comment]
>  > https://github.com/UjuiUjuMandan/EhViewer/actions/runs/10906382882
> > 
> > 这个版本应该会尊重自定义证书了。
> > 
> > 
> 
> 已确认：该版本配合自定义证书，已修复这个问题。👍

由衷赞美与感谢🙏

**Comment by UjuiUjuMandan** [comment]
> X浏览器

https://www.xbext.com/notifcations/notify-for-new-user/

> 赌博涉黄等非法网址是一些诈骗软件推广的聚集地，请不要从这些站点下载安装任何APP,这些app通常包含病毒木马，安装后会窃取您的私人信息导致财产损失。
>
> 国内应用市场上架的应用都经过了安全检测，请优先从应用市场安装应用。
>
> 微信搜索”国家反诈中心” 关注公众号，里面有很多关于防止诈骗的文章和视频帮助您了解更多反诈知识。

配合反诈宣传、默认关闭 TLS 校验、中国人开发。很明显这是一款 state-sponsored 间谍软件。
